/*
 * UAPI OpenAPI
 *
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using uapi-sdk-csharp.Model;
using uapi-sdk-csharp.Client;
using System.Reflection;

namespace uapi-sdk-csharp.Test.Model
{
    /// <summary>
    ///  Class for testing GetDictionaryLookup200ResponseEntryDefinitionsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetDictionaryLookup200ResponseEntryDefinitionsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetDictionaryLookup200ResponseEntryDefinitionsInner
        //private GetDictionaryLookup200ResponseEntryDefinitionsInner instance;

        public GetDictionaryLookup200ResponseEntryDefinitionsInnerTests()
        {
            // TODO uncomment below to create an instance of GetDictionaryLookup200ResponseEntryDefinitionsInner
            //instance = new GetDictionaryLookup200ResponseEntryDefinitionsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetDictionaryLookup200ResponseEntryDefinitionsInner
        /// </summary>
        [Fact]
        public void GetDictionaryLookup200ResponseEntryDefinitionsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetDictionaryLookup200ResponseEntryDefinitionsInner
            //Assert.IsType<GetDictionaryLookup200ResponseEntryDefinitionsInner>(instance);
        }

        /// <summary>
        /// Test the property 'Meaning'
        /// </summary>
        [Fact]
        public void MeaningTest()
        {
            // TODO unit test for the property 'Meaning'
        }

        /// <summary>
        /// Test the property 'PartOfSpeech'
        /// </summary>
        [Fact]
        public void PartOfSpeechTest()
        {
            // TODO unit test for the property 'PartOfSpeech'
        }
    }
}
