/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using uapi-sdk-csharp.Model;
using uapi-sdk-csharp.Client;
using System.Reflection;

namespace uapi-sdk-csharp.Test.Model
{
    /// <summary>
    ///  Class for testing GetGameSteamSummary200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetGameSteamSummary200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetGameSteamSummary200Response
        //private GetGameSteamSummary200Response instance;

        public GetGameSteamSummary200ResponseTests()
        {
            // TODO uncomment below to create an instance of GetGameSteamSummary200Response
            //instance = new GetGameSteamSummary200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetGameSteamSummary200Response
        /// </summary>
        [Fact]
        public void GetGameSteamSummary200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetGameSteamSummary200Response
            //Assert.IsType<GetGameSteamSummary200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Avatar'
        /// </summary>
        [Fact]
        public void AvatarTest()
        {
            // TODO unit test for the property 'Avatar'
        }

        /// <summary>
        /// Test the property 'Avatarfull'
        /// </summary>
        [Fact]
        public void AvatarfullTest()
        {
            // TODO unit test for the property 'Avatarfull'
        }

        /// <summary>
        /// Test the property 'Avatarmedium'
        /// </summary>
        [Fact]
        public void AvatarmediumTest()
        {
            // TODO unit test for the property 'Avatarmedium'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Communityvisibilitystate'
        /// </summary>
        [Fact]
        public void CommunityvisibilitystateTest()
        {
            // TODO unit test for the property 'Communityvisibilitystate'
        }

        /// <summary>
        /// Test the property 'Loccountrycode'
        /// </summary>
        [Fact]
        public void LoccountrycodeTest()
        {
            // TODO unit test for the property 'Loccountrycode'
        }

        /// <summary>
        /// Test the property 'Personaname'
        /// </summary>
        [Fact]
        public void PersonanameTest()
        {
            // TODO unit test for the property 'Personaname'
        }

        /// <summary>
        /// Test the property 'Personastate'
        /// </summary>
        [Fact]
        public void PersonastateTest()
        {
            // TODO unit test for the property 'Personastate'
        }

        /// <summary>
        /// Test the property 'Primaryclanid'
        /// </summary>
        [Fact]
        public void PrimaryclanidTest()
        {
            // TODO unit test for the property 'Primaryclanid'
        }

        /// <summary>
        /// Test the property 'Profilestate'
        /// </summary>
        [Fact]
        public void ProfilestateTest()
        {
            // TODO unit test for the property 'Profilestate'
        }

        /// <summary>
        /// Test the property 'Profileurl'
        /// </summary>
        [Fact]
        public void ProfileurlTest()
        {
            // TODO unit test for the property 'Profileurl'
        }

        /// <summary>
        /// Test the property 'Realname'
        /// </summary>
        [Fact]
        public void RealnameTest()
        {
            // TODO unit test for the property 'Realname'
        }

        /// <summary>
        /// Test the property 'Steamid'
        /// </summary>
        [Fact]
        public void SteamidTest()
        {
            // TODO unit test for the property 'Steamid'
        }

        /// <summary>
        /// Test the property 'Timecreated'
        /// </summary>
        [Fact]
        public void TimecreatedTest()
        {
            // TODO unit test for the property 'Timecreated'
        }

        /// <summary>
        /// Test the property 'TimecreatedStr'
        /// </summary>
        [Fact]
        public void TimecreatedStrTest()
        {
            // TODO unit test for the property 'TimecreatedStr'
        }
    }
}
