/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using uapi-sdk-csharp.Model;
using uapi-sdk-csharp.Client;
using System.Reflection;

namespace uapi-sdk-csharp.Test.Model
{
    /// <summary>
    ///  Class for testing GetGameMinecraftServerstatus400Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetGameMinecraftServerstatus400ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetGameMinecraftServerstatus400Response
        //private GetGameMinecraftServerstatus400Response instance;

        public GetGameMinecraftServerstatus400ResponseTests()
        {
            // TODO uncomment below to create an instance of GetGameMinecraftServerstatus400Response
            //instance = new GetGameMinecraftServerstatus400Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetGameMinecraftServerstatus400Response
        /// </summary>
        [Fact]
        public void GetGameMinecraftServerstatus400ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetGameMinecraftServerstatus400Response
            //Assert.IsType<GetGameMinecraftServerstatus400Response>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Details'
        /// </summary>
        [Fact]
        public void DetailsTest()
        {
            // TODO unit test for the property 'Details'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
