/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using uapi-sdk-csharp.Model;
using uapi-sdk-csharp.Client;
using System.Reflection;

namespace uapi-sdk-csharp.Test.Model
{
    /// <summary>
    ///  Class for testing GetGameMinecraftUserinfo200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetGameMinecraftUserinfo200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetGameMinecraftUserinfo200Response
        //private GetGameMinecraftUserinfo200Response instance;

        public GetGameMinecraftUserinfo200ResponseTests()
        {
            // TODO uncomment below to create an instance of GetGameMinecraftUserinfo200Response
            //instance = new GetGameMinecraftUserinfo200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetGameMinecraftUserinfo200Response
        /// </summary>
        [Fact]
        public void GetGameMinecraftUserinfo200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetGameMinecraftUserinfo200Response
            //Assert.IsType<GetGameMinecraftUserinfo200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'SkinUrl'
        /// </summary>
        [Fact]
        public void SkinUrlTest()
        {
            // TODO unit test for the property 'SkinUrl'
        }

        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }

        /// <summary>
        /// Test the property 'Uuid'
        /// </summary>
        [Fact]
        public void UuidTest()
        {
            // TODO unit test for the property 'Uuid'
        }
    }
}
