/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using uapi-sdk-csharp.Model;
using uapi-sdk-csharp.Client;
using System.Reflection;

namespace uapi-sdk-csharp.Test.Model
{
    /// <summary>
    ///  Class for testing GetGameMinecraftHistoryid200ResponseHistoryInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetGameMinecraftHistoryid200ResponseHistoryInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetGameMinecraftHistoryid200ResponseHistoryInner
        //private GetGameMinecraftHistoryid200ResponseHistoryInner instance;

        public GetGameMinecraftHistoryid200ResponseHistoryInnerTests()
        {
            // TODO uncomment below to create an instance of GetGameMinecraftHistoryid200ResponseHistoryInner
            //instance = new GetGameMinecraftHistoryid200ResponseHistoryInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetGameMinecraftHistoryid200ResponseHistoryInner
        /// </summary>
        [Fact]
        public void GetGameMinecraftHistoryid200ResponseHistoryInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetGameMinecraftHistoryid200ResponseHistoryInner
            //Assert.IsType<GetGameMinecraftHistoryid200ResponseHistoryInner>(instance);
        }

        /// <summary>
        /// Test the property 'ChangedToAt'
        /// </summary>
        [Fact]
        public void ChangedToAtTest()
        {
            // TODO unit test for the property 'ChangedToAt'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
    }
}
