/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using uapi-sdk-csharp.Model;
using uapi-sdk-csharp.Client;
using System.Reflection;

namespace uapi-sdk-csharp.Test.Model
{
    /// <summary>
    ///  Class for testing GetMiscLunartime200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetMiscLunartime200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetMiscLunartime200Response
        //private GetMiscLunartime200Response instance;

        public GetMiscLunartime200ResponseTests()
        {
            // TODO uncomment below to create an instance of GetMiscLunartime200Response
            //instance = new GetMiscLunartime200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetMiscLunartime200Response
        /// </summary>
        [Fact]
        public void GetMiscLunartime200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetMiscLunartime200Response
            //Assert.IsType<GetMiscLunartime200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
