/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using uapi-sdk-csharp.Model;
using uapi-sdk-csharp.Client;
using System.Reflection;

namespace uapi-sdk-csharp.Test.Model
{
    /// <summary>
    ///  Class for testing GetMiscWeather200ResponseMinutelyPrecip
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetMiscWeather200ResponseMinutelyPrecipTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetMiscWeather200ResponseMinutelyPrecip
        //private GetMiscWeather200ResponseMinutelyPrecip instance;

        public GetMiscWeather200ResponseMinutelyPrecipTests()
        {
            // TODO uncomment below to create an instance of GetMiscWeather200ResponseMinutelyPrecip
            //instance = new GetMiscWeather200ResponseMinutelyPrecip();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetMiscWeather200ResponseMinutelyPrecip
        /// </summary>
        [Fact]
        public void GetMiscWeather200ResponseMinutelyPrecipInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetMiscWeather200ResponseMinutelyPrecip
            //Assert.IsType<GetMiscWeather200ResponseMinutelyPrecip>(instance);
        }

        /// <summary>
        /// Test the property 'Summary'
        /// </summary>
        [Fact]
        public void SummaryTest()
        {
            // TODO unit test for the property 'Summary'
        }

        /// <summary>
        /// Test the property 'UpdateTime'
        /// </summary>
        [Fact]
        public void UpdateTimeTest()
        {
            // TODO unit test for the property 'UpdateTime'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
