/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using uapi-sdk-csharp.Model;
using uapi-sdk-csharp.Client;
using System.Reflection;

namespace uapi-sdk-csharp.Test.Model
{
    /// <summary>
    ///  Class for testing GetMiscHolidayCalendar200ResponseDataNearbyNextInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetMiscHolidayCalendar200ResponseDataNearbyNextInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetMiscHolidayCalendar200ResponseDataNearbyNextInner
        //private GetMiscHolidayCalendar200ResponseDataNearbyNextInner instance;

        public GetMiscHolidayCalendar200ResponseDataNearbyNextInnerTests()
        {
            // TODO uncomment below to create an instance of GetMiscHolidayCalendar200ResponseDataNearbyNextInner
            //instance = new GetMiscHolidayCalendar200ResponseDataNearbyNextInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetMiscHolidayCalendar200ResponseDataNearbyNextInner
        /// </summary>
        [Fact]
        public void GetMiscHolidayCalendar200ResponseDataNearbyNextInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetMiscHolidayCalendar200ResponseDataNearbyNextInner
            //Assert.IsType<GetMiscHolidayCalendar200ResponseDataNearbyNextInner>(instance);
        }

        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
    }
}
