/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using uapi-sdk-csharp.Model;
using uapi-sdk-csharp.Client;
using System.Reflection;

namespace uapi-sdk-csharp.Test.Model
{
    /// <summary>
    ///  Class for testing GetMiscTrackingDetect200ResponseDataAlternativesInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetMiscTrackingDetect200ResponseDataAlternativesInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetMiscTrackingDetect200ResponseDataAlternativesInner
        //private GetMiscTrackingDetect200ResponseDataAlternativesInner instance;

        public GetMiscTrackingDetect200ResponseDataAlternativesInnerTests()
        {
            // TODO uncomment below to create an instance of GetMiscTrackingDetect200ResponseDataAlternativesInner
            //instance = new GetMiscTrackingDetect200ResponseDataAlternativesInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetMiscTrackingDetect200ResponseDataAlternativesInner
        /// </summary>
        [Fact]
        public void GetMiscTrackingDetect200ResponseDataAlternativesInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetMiscTrackingDetect200ResponseDataAlternativesInner
            //Assert.IsType<GetMiscTrackingDetect200ResponseDataAlternativesInner>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
    }
}
