/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using uapi-sdk-csharp.Model;
using uapi-sdk-csharp.Client;
using System.Reflection;

namespace uapi-sdk-csharp.Test.Model
{
    /// <summary>
    ///  Class for testing GetNetworkWhois200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetNetworkWhois200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetNetworkWhois200Response
        //private GetNetworkWhois200Response instance;

        public GetNetworkWhois200ResponseTests()
        {
            // TODO uncomment below to create an instance of GetNetworkWhois200Response
            //instance = new GetNetworkWhois200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetNetworkWhois200Response
        /// </summary>
        [Fact]
        public void GetNetworkWhois200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetNetworkWhois200Response
            //Assert.IsType<GetNetworkWhois200Response>(instance);
        }
    }
}
