/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using uapi-sdk-csharp.Model;
using uapi-sdk-csharp.Client;
using System.Reflection;

namespace uapi-sdk-csharp.Test.Model
{
    /// <summary>
    ///  Class for testing GetRandomImage404Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetRandomImage404ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetRandomImage404Response
        //private GetRandomImage404Response instance;

        public GetRandomImage404ResponseTests()
        {
            // TODO uncomment below to create an instance of GetRandomImage404Response
            //instance = new GetRandomImage404Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetRandomImage404Response
        /// </summary>
        [Fact]
        public void GetRandomImage404ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetRandomImage404Response
            //Assert.IsType<GetRandomImage404Response>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
