/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using uapi-sdk-csharp.Model;
using uapi-sdk-csharp.Client;
using System.Reflection;

namespace uapi-sdk-csharp.Test.Model
{
    /// <summary>
    ///  Class for testing GetSocialBilibiliVideoinfo200ResponseDimension
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetSocialBilibiliVideoinfo200ResponseDimensionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetSocialBilibiliVideoinfo200ResponseDimension
        //private GetSocialBilibiliVideoinfo200ResponseDimension instance;

        public GetSocialBilibiliVideoinfo200ResponseDimensionTests()
        {
            // TODO uncomment below to create an instance of GetSocialBilibiliVideoinfo200ResponseDimension
            //instance = new GetSocialBilibiliVideoinfo200ResponseDimension();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetSocialBilibiliVideoinfo200ResponseDimension
        /// </summary>
        [Fact]
        public void GetSocialBilibiliVideoinfo200ResponseDimensionInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetSocialBilibiliVideoinfo200ResponseDimension
            //Assert.IsType<GetSocialBilibiliVideoinfo200ResponseDimension>(instance);
        }

        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Fact]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }

        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Fact]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }

        /// <summary>
        /// Test the property 'Rotate'
        /// </summary>
        [Fact]
        public void RotateTest()
        {
            // TODO unit test for the property 'Rotate'
        }
    }
}
