/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using uapi-sdk-csharp.Model;
using uapi-sdk-csharp.Client;
using System.Reflection;

namespace uapi-sdk-csharp.Test.Model
{
    /// <summary>
    ///  Class for testing GetWebTomarkdownAsyncStatus200ResponseAnyOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetWebTomarkdownAsyncStatus200ResponseAnyOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetWebTomarkdownAsyncStatus200ResponseAnyOf
        //private GetWebTomarkdownAsyncStatus200ResponseAnyOf instance;

        public GetWebTomarkdownAsyncStatus200ResponseAnyOfTests()
        {
            // TODO uncomment below to create an instance of GetWebTomarkdownAsyncStatus200ResponseAnyOf
            //instance = new GetWebTomarkdownAsyncStatus200ResponseAnyOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetWebTomarkdownAsyncStatus200ResponseAnyOf
        /// </summary>
        [Fact]
        public void GetWebTomarkdownAsyncStatus200ResponseAnyOfInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetWebTomarkdownAsyncStatus200ResponseAnyOf
            //Assert.IsType<GetWebTomarkdownAsyncStatus200ResponseAnyOf>(instance);
        }

        /// <summary>
        /// Test the property 'TaskId'
        /// </summary>
        [Fact]
        public void TaskIdTest()
        {
            // TODO unit test for the property 'TaskId'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'Progress'
        /// </summary>
        [Fact]
        public void ProgressTest()
        {
            // TODO unit test for the property 'Progress'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
