/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using uapi-sdk-csharp.Model;
using uapi-sdk-csharp.Client;
using System.Reflection;

namespace uapi-sdk-csharp.Test.Model
{
    /// <summary>
    ///  Class for testing PostSearchAggregate200ResponseMetadataRequestParams
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PostSearchAggregate200ResponseMetadataRequestParamsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PostSearchAggregate200ResponseMetadataRequestParams
        //private PostSearchAggregate200ResponseMetadataRequestParams instance;

        public PostSearchAggregate200ResponseMetadataRequestParamsTests()
        {
            // TODO uncomment below to create an instance of PostSearchAggregate200ResponseMetadataRequestParams
            //instance = new PostSearchAggregate200ResponseMetadataRequestParams();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PostSearchAggregate200ResponseMetadataRequestParams
        /// </summary>
        [Fact]
        public void PostSearchAggregate200ResponseMetadataRequestParamsInstanceTest()
        {
            // TODO uncomment below to test "IsType" PostSearchAggregate200ResponseMetadataRequestParams
            //Assert.IsType<PostSearchAggregate200ResponseMetadataRequestParams>(instance);
        }

        /// <summary>
        /// Test the property 'Query'
        /// </summary>
        [Fact]
        public void QueryTest()
        {
            // TODO unit test for the property 'Query'
        }

        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Fact]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }

        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Fact]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }

        /// <summary>
        /// Test the property 'TimeoutMs'
        /// </summary>
        [Fact]
        public void TimeoutMsTest()
        {
            // TODO unit test for the property 'TimeoutMs'
        }

        /// <summary>
        /// Test the property 'Sort'
        /// </summary>
        [Fact]
        public void SortTest()
        {
            // TODO unit test for the property 'Sort'
        }
    }
}
