/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using uapi-sdk-csharp.Model;
using uapi-sdk-csharp.Client;
using System.Reflection;

namespace uapi-sdk-csharp.Test.Model
{
    /// <summary>
    ///  Class for testing PostTextMarkdownToHtml200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PostTextMarkdownToHtml200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PostTextMarkdownToHtml200Response
        //private PostTextMarkdownToHtml200Response instance;

        public PostTextMarkdownToHtml200ResponseTests()
        {
            // TODO uncomment below to create an instance of PostTextMarkdownToHtml200Response
            //instance = new PostTextMarkdownToHtml200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PostTextMarkdownToHtml200Response
        /// </summary>
        [Fact]
        public void PostTextMarkdownToHtml200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PostTextMarkdownToHtml200Response
            //Assert.IsType<PostTextMarkdownToHtml200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
