/*
 * UAPI OpenAPI
 *
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using uapi-sdk-csharp.Model;
using uapi-sdk-csharp.Client;
using System.Reflection;

namespace uapi-sdk-csharp.Test.Model
{
    /// <summary>
    ///  Class for testing PostWatermarkEmbed413Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PostWatermarkEmbed413ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PostWatermarkEmbed413Response
        //private PostWatermarkEmbed413Response instance;

        public PostWatermarkEmbed413ResponseTests()
        {
            // TODO uncomment below to create an instance of PostWatermarkEmbed413Response
            //instance = new PostWatermarkEmbed413Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PostWatermarkEmbed413Response
        /// </summary>
        [Fact]
        public void PostWatermarkEmbed413ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PostWatermarkEmbed413Response
            //Assert.IsType<PostWatermarkEmbed413Response>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
