/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using uapi-sdk-csharp.Model;
using uapi-sdk-csharp.Client;
using System.Reflection;

namespace uapi-sdk-csharp.Test.Model
{
    /// <summary>
    ///  Class for testing PostTextMarkdownToPdf400ResponseOneOf1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PostTextMarkdownToPdf400ResponseOneOf1Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PostTextMarkdownToPdf400ResponseOneOf1
        //private PostTextMarkdownToPdf400ResponseOneOf1 instance;

        public PostTextMarkdownToPdf400ResponseOneOf1Tests()
        {
            // TODO uncomment below to create an instance of PostTextMarkdownToPdf400ResponseOneOf1
            //instance = new PostTextMarkdownToPdf400ResponseOneOf1();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PostTextMarkdownToPdf400ResponseOneOf1
        /// </summary>
        [Fact]
        public void PostTextMarkdownToPdf400ResponseOneOf1InstanceTest()
        {
            // TODO uncomment below to test "IsType" PostTextMarkdownToPdf400ResponseOneOf1
            //Assert.IsType<PostTextMarkdownToPdf400ResponseOneOf1>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
