/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using uapi-sdk-csharp.Model;
using uapi-sdk-csharp.Client;
using System.Reflection;

namespace uapi-sdk-csharp.Test.Model
{
    /// <summary>
    ///  Class for testing PostTextAesDecrypt200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PostTextAesDecrypt200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PostTextAesDecrypt200Response
        //private PostTextAesDecrypt200Response instance;

        public PostTextAesDecrypt200ResponseTests()
        {
            // TODO uncomment below to create an instance of PostTextAesDecrypt200Response
            //instance = new PostTextAesDecrypt200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PostTextAesDecrypt200Response
        /// </summary>
        [Fact]
        public void PostTextAesDecrypt200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PostTextAesDecrypt200Response
            //Assert.IsType<PostTextAesDecrypt200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Plaintext'
        /// </summary>
        [Fact]
        public void PlaintextTest()
        {
            // TODO unit test for the property 'Plaintext'
        }
    }
}
