/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using uapi-sdk-csharp.Model;
using uapi-sdk-csharp.Client;
using System.Reflection;

namespace uapi-sdk-csharp.Test.Model
{
    /// <summary>
    ///  Class for testing PostTextMd5Request
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PostTextMd5RequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PostTextMd5Request
        //private PostTextMd5Request instance;

        public PostTextMd5RequestTests()
        {
            // TODO uncomment below to create an instance of PostTextMd5Request
            //instance = new PostTextMd5Request();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PostTextMd5Request
        /// </summary>
        [Fact]
        public void PostTextMd5RequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PostTextMd5Request
            //Assert.IsType<PostTextMd5Request>(instance);
        }

        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
    }
}
