/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using uapi-sdk-csharp.Model;
using uapi-sdk-csharp.Client;
using System.Reflection;

namespace uapi-sdk-csharp.Test.Model
{
    /// <summary>
    ///  Class for testing PostAiTranslate200ResponseBatchSummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PostAiTranslate200ResponseBatchSummaryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PostAiTranslate200ResponseBatchSummary
        //private PostAiTranslate200ResponseBatchSummary instance;

        public PostAiTranslate200ResponseBatchSummaryTests()
        {
            // TODO uncomment below to create an instance of PostAiTranslate200ResponseBatchSummary
            //instance = new PostAiTranslate200ResponseBatchSummary();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PostAiTranslate200ResponseBatchSummary
        /// </summary>
        [Fact]
        public void PostAiTranslate200ResponseBatchSummaryInstanceTest()
        {
            // TODO uncomment below to test "IsType" PostAiTranslate200ResponseBatchSummary
            //Assert.IsType<PostAiTranslate200ResponseBatchSummary>(instance);
        }

        /// <summary>
        /// Test the property 'TotalItems'
        /// </summary>
        [Fact]
        public void TotalItemsTest()
        {
            // TODO unit test for the property 'TotalItems'
        }

        /// <summary>
        /// Test the property 'SuccessItems'
        /// </summary>
        [Fact]
        public void SuccessItemsTest()
        {
            // TODO unit test for the property 'SuccessItems'
        }

        /// <summary>
        /// Test the property 'FailedItems'
        /// </summary>
        [Fact]
        public void FailedItemsTest()
        {
            // TODO unit test for the property 'FailedItems'
        }

        /// <summary>
        /// Test the property 'AverageQuality'
        /// </summary>
        [Fact]
        public void AverageQualityTest()
        {
            // TODO unit test for the property 'AverageQuality'
        }
    }
}
