/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using uapi-sdk-csharp.Model;
using uapi-sdk-csharp.Client;
using System.Reflection;

namespace uapi-sdk-csharp.Test.Model
{
    /// <summary>
    ///  Class for testing PostSearchAggregate200ResponseMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PostSearchAggregate200ResponseMetadataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PostSearchAggregate200ResponseMetadata
        //private PostSearchAggregate200ResponseMetadata instance;

        public PostSearchAggregate200ResponseMetadataTests()
        {
            // TODO uncomment below to create an instance of PostSearchAggregate200ResponseMetadata
            //instance = new PostSearchAggregate200ResponseMetadata();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PostSearchAggregate200ResponseMetadata
        /// </summary>
        [Fact]
        public void PostSearchAggregate200ResponseMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsType" PostSearchAggregate200ResponseMetadata
            //Assert.IsType<PostSearchAggregate200ResponseMetadata>(instance);
        }

        /// <summary>
        /// Test the property 'RequestParams'
        /// </summary>
        [Fact]
        public void RequestParamsTest()
        {
            // TODO unit test for the property 'RequestParams'
        }

        /// <summary>
        /// Test the property 'DedupeRemoved'
        /// </summary>
        [Fact]
        public void DedupeRemovedTest()
        {
            // TODO unit test for the property 'DedupeRemoved'
        }

        /// <summary>
        /// Test the property 'RerankApplied'
        /// </summary>
        [Fact]
        public void RerankAppliedTest()
        {
            // TODO unit test for the property 'RerankApplied'
        }

        /// <summary>
        /// Test the property 'ContentFetched'
        /// </summary>
        [Fact]
        public void ContentFetchedTest()
        {
            // TODO unit test for the property 'ContentFetched'
        }
    }
}
