/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using uapi-sdk-csharp.Model;
using uapi-sdk-csharp.Client;
using System.Reflection;

namespace uapi-sdk-csharp.Test.Model
{
    /// <summary>
    ///  Class for testing PostImageDecode503Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PostImageDecode503ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PostImageDecode503Response
        //private PostImageDecode503Response instance;

        public PostImageDecode503ResponseTests()
        {
            // TODO uncomment below to create an instance of PostImageDecode503Response
            //instance = new PostImageDecode503Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PostImageDecode503Response
        /// </summary>
        [Fact]
        public void PostImageDecode503ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PostImageDecode503Response
            //Assert.IsType<PostImageDecode503Response>(instance);
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
    }
}
