/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using uapi-sdk-csharp.Model;
using uapi-sdk-csharp.Client;
using System.Reflection;

namespace uapi-sdk-csharp.Test.Model
{
    /// <summary>
    ///  Class for testing PostTranslateStream400Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PostTranslateStream400ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PostTranslateStream400Response
        //private PostTranslateStream400Response instance;

        public PostTranslateStream400ResponseTests()
        {
            // TODO uncomment below to create an instance of PostTranslateStream400Response
            //instance = new PostTranslateStream400Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PostTranslateStream400Response
        /// </summary>
        [Fact]
        public void PostTranslateStream400ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PostTranslateStream400Response
            //Assert.IsType<PostTranslateStream400Response>(instance);
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
    }
}
