// <auto-generated>
/*
 * UAPI OpenAPI
 *
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using uapi-sdk-csharp.Client;

namespace uapi-sdk-csharp.Model
{
    /// <summary>
    /// GetGithubUser404Response
    /// </summary>
    public partial class GetGithubUser404Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetGithubUser404Response" /> class.
        /// </summary>
        /// <param name="code">错误码。</param>
        /// <param name="error">错误原因说明。</param>
        [JsonConstructor]
        public GetGithubUser404Response(Option<string?> code = default, Option<string?> error = default)
        {
            CodeOption = code;
            ErrorOption = error;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Code
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CodeOption { get; private set; }

        /// <summary>
        /// 错误码。
        /// </summary>
        /// <value>错误码。</value>
        /* <example>USER_NOT_FOUND</example> */
        [JsonPropertyName("code")]
        public string? Code { get { return this.CodeOption; } set { this.CodeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Error
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ErrorOption { get; private set; }

        /// <summary>
        /// 错误原因说明。
        /// </summary>
        /// <value>错误原因说明。</value>
        /* <example>未找到对应的 GitHub 用户</example> */
        [JsonPropertyName("error")]
        public string? Error { get { return this.ErrorOption; } set { this.ErrorOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetGithubUser404Response {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetGithubUser404Response" />
    /// </summary>
    public class GetGithubUser404ResponseJsonConverter : JsonConverter<GetGithubUser404Response>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetGithubUser404Response" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetGithubUser404Response Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> code = default;
            Option<string?> error = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "code":
                            code = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "error":
                            error = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (code.IsSet && code.Value == null)
                throw new ArgumentNullException(nameof(code), "Property is not nullable for class GetGithubUser404Response.");

            if (error.IsSet && error.Value == null)
                throw new ArgumentNullException(nameof(error), "Property is not nullable for class GetGithubUser404Response.");

            return new GetGithubUser404Response(code, error);
        }

        /// <summary>
        /// Serializes a <see cref="GetGithubUser404Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getGithubUser404Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetGithubUser404Response getGithubUser404Response, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getGithubUser404Response, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetGithubUser404Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getGithubUser404Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetGithubUser404Response getGithubUser404Response, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getGithubUser404Response.CodeOption.IsSet && getGithubUser404Response.Code == null)
                throw new ArgumentNullException(nameof(getGithubUser404Response.Code), "Property is required for class GetGithubUser404Response.");

            if (getGithubUser404Response.ErrorOption.IsSet && getGithubUser404Response.Error == null)
                throw new ArgumentNullException(nameof(getGithubUser404Response.Error), "Property is required for class GetGithubUser404Response.");

            if (getGithubUser404Response.CodeOption.IsSet)
                writer.WriteString("code", getGithubUser404Response.Code);

            if (getGithubUser404Response.ErrorOption.IsSet)
                writer.WriteString("error", getGithubUser404Response.Error);
        }
    }
}
