// <auto-generated>
/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using uapi-sdk-csharp.Client;

namespace uapi-sdk-csharp.Model
{
    /// <summary>
    /// GetMiscTrackingQuery200Response
    /// </summary>
    public partial class GetMiscTrackingQuery200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetMiscTrackingQuery200Response" /> class.
        /// </summary>
        /// <param name="trackingNumber">快递单号</param>
        /// <param name="carrierCode">快递公司编码</param>
        /// <param name="carrierName">快递公司名称</param>
        /// <param name="trackCount">物流轨迹数量</param>
        /// <param name="tracks">物流轨迹列表，按时间倒序排列</param>
        [JsonConstructor]
        public GetMiscTrackingQuery200Response(Option<string?> trackingNumber = default, Option<string?> carrierCode = default, Option<string?> carrierName = default, Option<int?> trackCount = default, Option<List<GetMiscTrackingQuery200ResponseTracksInner>?> tracks = default)
        {
            TrackingNumberOption = trackingNumber;
            CarrierCodeOption = carrierCode;
            CarrierNameOption = carrierName;
            TrackCountOption = trackCount;
            TracksOption = tracks;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of TrackingNumber
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TrackingNumberOption { get; private set; }

        /// <summary>
        /// 快递单号
        /// </summary>
        /// <value>快递单号</value>
        /* <example>YT1234567890123</example> */
        [JsonPropertyName("tracking_number")]
        public string? TrackingNumber { get { return this.TrackingNumberOption; } set { this.TrackingNumberOption = new(value); } }

        /// <summary>
        /// Used to track the state of CarrierCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CarrierCodeOption { get; private set; }

        /// <summary>
        /// 快递公司编码
        /// </summary>
        /// <value>快递公司编码</value>
        /* <example>yuantong</example> */
        [JsonPropertyName("carrier_code")]
        public string? CarrierCode { get { return this.CarrierCodeOption; } set { this.CarrierCodeOption = new(value); } }

        /// <summary>
        /// Used to track the state of CarrierName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CarrierNameOption { get; private set; }

        /// <summary>
        /// 快递公司名称
        /// </summary>
        /// <value>快递公司名称</value>
        /* <example>圆通速递</example> */
        [JsonPropertyName("carrier_name")]
        public string? CarrierName { get { return this.CarrierNameOption; } set { this.CarrierNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of TrackCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> TrackCountOption { get; private set; }

        /// <summary>
        /// 物流轨迹数量
        /// </summary>
        /// <value>物流轨迹数量</value>
        /* <example>3</example> */
        [JsonPropertyName("track_count")]
        public int? TrackCount { get { return this.TrackCountOption; } set { this.TrackCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of Tracks
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<GetMiscTrackingQuery200ResponseTracksInner>?> TracksOption { get; private set; }

        /// <summary>
        /// 物流轨迹列表，按时间倒序排列
        /// </summary>
        /// <value>物流轨迹列表，按时间倒序排列</value>
        [JsonPropertyName("tracks")]
        public List<GetMiscTrackingQuery200ResponseTracksInner>? Tracks { get { return this.TracksOption; } set { this.TracksOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetMiscTrackingQuery200Response {\n");
            sb.Append("  TrackingNumber: ").Append(TrackingNumber).Append("\n");
            sb.Append("  CarrierCode: ").Append(CarrierCode).Append("\n");
            sb.Append("  CarrierName: ").Append(CarrierName).Append("\n");
            sb.Append("  TrackCount: ").Append(TrackCount).Append("\n");
            sb.Append("  Tracks: ").Append(Tracks).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetMiscTrackingQuery200Response" />
    /// </summary>
    public class GetMiscTrackingQuery200ResponseJsonConverter : JsonConverter<GetMiscTrackingQuery200Response>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetMiscTrackingQuery200Response" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetMiscTrackingQuery200Response Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> trackingNumber = default;
            Option<string?> carrierCode = default;
            Option<string?> carrierName = default;
            Option<int?> trackCount = default;
            Option<List<GetMiscTrackingQuery200ResponseTracksInner>?> tracks = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "tracking_number":
                            trackingNumber = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "carrier_code":
                            carrierCode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "carrier_name":
                            carrierName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "track_count":
                            trackCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "tracks":
                            tracks = new Option<List<GetMiscTrackingQuery200ResponseTracksInner>?>(JsonSerializer.Deserialize<List<GetMiscTrackingQuery200ResponseTracksInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (trackingNumber.IsSet && trackingNumber.Value == null)
                throw new ArgumentNullException(nameof(trackingNumber), "Property is not nullable for class GetMiscTrackingQuery200Response.");

            if (carrierCode.IsSet && carrierCode.Value == null)
                throw new ArgumentNullException(nameof(carrierCode), "Property is not nullable for class GetMiscTrackingQuery200Response.");

            if (carrierName.IsSet && carrierName.Value == null)
                throw new ArgumentNullException(nameof(carrierName), "Property is not nullable for class GetMiscTrackingQuery200Response.");

            if (trackCount.IsSet && trackCount.Value == null)
                throw new ArgumentNullException(nameof(trackCount), "Property is not nullable for class GetMiscTrackingQuery200Response.");

            if (tracks.IsSet && tracks.Value == null)
                throw new ArgumentNullException(nameof(tracks), "Property is not nullable for class GetMiscTrackingQuery200Response.");

            return new GetMiscTrackingQuery200Response(trackingNumber, carrierCode, carrierName, trackCount, tracks);
        }

        /// <summary>
        /// Serializes a <see cref="GetMiscTrackingQuery200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getMiscTrackingQuery200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetMiscTrackingQuery200Response getMiscTrackingQuery200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getMiscTrackingQuery200Response, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetMiscTrackingQuery200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getMiscTrackingQuery200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetMiscTrackingQuery200Response getMiscTrackingQuery200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getMiscTrackingQuery200Response.TrackingNumberOption.IsSet && getMiscTrackingQuery200Response.TrackingNumber == null)
                throw new ArgumentNullException(nameof(getMiscTrackingQuery200Response.TrackingNumber), "Property is required for class GetMiscTrackingQuery200Response.");

            if (getMiscTrackingQuery200Response.CarrierCodeOption.IsSet && getMiscTrackingQuery200Response.CarrierCode == null)
                throw new ArgumentNullException(nameof(getMiscTrackingQuery200Response.CarrierCode), "Property is required for class GetMiscTrackingQuery200Response.");

            if (getMiscTrackingQuery200Response.CarrierNameOption.IsSet && getMiscTrackingQuery200Response.CarrierName == null)
                throw new ArgumentNullException(nameof(getMiscTrackingQuery200Response.CarrierName), "Property is required for class GetMiscTrackingQuery200Response.");

            if (getMiscTrackingQuery200Response.TracksOption.IsSet && getMiscTrackingQuery200Response.Tracks == null)
                throw new ArgumentNullException(nameof(getMiscTrackingQuery200Response.Tracks), "Property is required for class GetMiscTrackingQuery200Response.");

            if (getMiscTrackingQuery200Response.TrackingNumberOption.IsSet)
                writer.WriteString("tracking_number", getMiscTrackingQuery200Response.TrackingNumber);

            if (getMiscTrackingQuery200Response.CarrierCodeOption.IsSet)
                writer.WriteString("carrier_code", getMiscTrackingQuery200Response.CarrierCode);

            if (getMiscTrackingQuery200Response.CarrierNameOption.IsSet)
                writer.WriteString("carrier_name", getMiscTrackingQuery200Response.CarrierName);

            if (getMiscTrackingQuery200Response.TrackCountOption.IsSet)
                writer.WriteNumber("track_count", getMiscTrackingQuery200Response.TrackCountOption.Value!.Value);

            if (getMiscTrackingQuery200Response.TracksOption.IsSet)
            {
                writer.WritePropertyName("tracks");
                JsonSerializer.Serialize(writer, getMiscTrackingQuery200Response.Tracks, jsonSerializerOptions);
            }
        }
    }
}
