// <auto-generated>
/*
 * UAPI OpenAPI
 *
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using uapi-sdk-csharp.Client;

namespace uapi-sdk-csharp.Model
{
    /// <summary>
    /// GetMiscWeather200ResponseHourlyForecastInner
    /// </summary>
    public partial class GetMiscWeather200ResponseHourlyForecastInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetMiscWeather200ResponseHourlyForecastInner" /> class.
        /// </summary>
        /// <param name="feelsLike">体感温度 °C（可选）</param>
        /// <param name="humidity">湿度 %（可选）</param>
        /// <param name="pop">降水概率 %（可选）</param>
        /// <param name="precip">降水量 mm（可选）</param>
        /// <param name="temperature">温度 °C</param>
        /// <param name="time">预报时间（ISO8601 或 YYYY-MM-DD HH:MM）</param>
        /// <param name="uvIndex">紫外线指数（可选，国内城市通常不返回）</param>
        /// <param name="visibility">能见度 km（可选）</param>
        /// <param name="weather">天气状况</param>
        /// <param name="windDirection">风向（可选）</param>
        /// <param name="windScale">风力等级（可选）</param>
        /// <param name="windSpeed">风速 km/h（可选）</param>
        [JsonConstructor]
        public GetMiscWeather200ResponseHourlyForecastInner(Option<decimal?> feelsLike = default, Option<decimal?> humidity = default, Option<decimal?> pop = default, Option<decimal?> precip = default, Option<decimal?> temperature = default, Option<string?> time = default, Option<decimal?> uvIndex = default, Option<decimal?> visibility = default, Option<string?> weather = default, Option<string?> windDirection = default, Option<string?> windScale = default, Option<decimal?> windSpeed = default)
        {
            FeelsLikeOption = feelsLike;
            HumidityOption = humidity;
            PopOption = pop;
            PrecipOption = precip;
            TemperatureOption = temperature;
            TimeOption = time;
            UvIndexOption = uvIndex;
            VisibilityOption = visibility;
            WeatherOption = weather;
            WindDirectionOption = windDirection;
            WindScaleOption = windScale;
            WindSpeedOption = windSpeed;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of FeelsLike
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> FeelsLikeOption { get; private set; }

        /// <summary>
        /// 体感温度 °C（可选）
        /// </summary>
        /// <value>体感温度 °C（可选）</value>
        /* <example>6</example> */
        [JsonPropertyName("feels_like")]
        public decimal? FeelsLike { get { return this.FeelsLikeOption; } set { this.FeelsLikeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Humidity
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> HumidityOption { get; private set; }

        /// <summary>
        /// 湿度 %（可选）
        /// </summary>
        /// <value>湿度 %（可选）</value>
        /* <example>25</example> */
        [JsonPropertyName("humidity")]
        public decimal? Humidity { get { return this.HumidityOption; } set { this.HumidityOption = new(value); } }

        /// <summary>
        /// Used to track the state of Pop
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> PopOption { get; private set; }

        /// <summary>
        /// 降水概率 %（可选）
        /// </summary>
        /// <value>降水概率 %（可选）</value>
        /* <example>0</example> */
        [JsonPropertyName("pop")]
        public decimal? Pop { get { return this.PopOption; } set { this.PopOption = new(value); } }

        /// <summary>
        /// Used to track the state of Precip
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> PrecipOption { get; private set; }

        /// <summary>
        /// 降水量 mm（可选）
        /// </summary>
        /// <value>降水量 mm（可选）</value>
        /* <example>0</example> */
        [JsonPropertyName("precip")]
        public decimal? Precip { get { return this.PrecipOption; } set { this.PrecipOption = new(value); } }

        /// <summary>
        /// Used to track the state of Temperature
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> TemperatureOption { get; private set; }

        /// <summary>
        /// 温度 °C
        /// </summary>
        /// <value>温度 °C</value>
        /* <example>8</example> */
        [JsonPropertyName("temperature")]
        public decimal? Temperature { get { return this.TemperatureOption; } set { this.TemperatureOption = new(value); } }

        /// <summary>
        /// Used to track the state of Time
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TimeOption { get; private set; }

        /// <summary>
        /// 预报时间（ISO8601 或 YYYY-MM-DD HH:MM）
        /// </summary>
        /// <value>预报时间（ISO8601 或 YYYY-MM-DD HH:MM）</value>
        /* <example>2026-02-19T17:00:00+0900</example> */
        [JsonPropertyName("time")]
        public string? Time { get { return this.TimeOption; } set { this.TimeOption = new(value); } }

        /// <summary>
        /// Used to track the state of UvIndex
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> UvIndexOption { get; private set; }

        /// <summary>
        /// 紫外线指数（可选，国内城市通常不返回）
        /// </summary>
        /// <value>紫外线指数（可选，国内城市通常不返回）</value>
        /* <example>0</example> */
        [JsonPropertyName("uv_index")]
        public decimal? UvIndex { get { return this.UvIndexOption; } set { this.UvIndexOption = new(value); } }

        /// <summary>
        /// Used to track the state of Visibility
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> VisibilityOption { get; private set; }

        /// <summary>
        /// 能见度 km（可选）
        /// </summary>
        /// <value>能见度 km（可选）</value>
        /* <example>14</example> */
        [JsonPropertyName("visibility")]
        public decimal? Visibility { get { return this.VisibilityOption; } set { this.VisibilityOption = new(value); } }

        /// <summary>
        /// Used to track the state of Weather
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> WeatherOption { get; private set; }

        /// <summary>
        /// 天气状况
        /// </summary>
        /// <value>天气状况</value>
        /* <example>晴</example> */
        [JsonPropertyName("weather")]
        public string? Weather { get { return this.WeatherOption; } set { this.WeatherOption = new(value); } }

        /// <summary>
        /// Used to track the state of WindDirection
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> WindDirectionOption { get; private set; }

        /// <summary>
        /// 风向（可选）
        /// </summary>
        /// <value>风向（可选）</value>
        /* <example>北北西</example> */
        [JsonPropertyName("wind_direction")]
        public string? WindDirection { get { return this.WindDirectionOption; } set { this.WindDirectionOption = new(value); } }

        /// <summary>
        /// Used to track the state of WindScale
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> WindScaleOption { get; private set; }

        /// <summary>
        /// 风力等级（可选）
        /// </summary>
        /// <value>风力等级（可选）</value>
        /* <example>3级</example> */
        [JsonPropertyName("wind_scale")]
        public string? WindScale { get { return this.WindScaleOption; } set { this.WindScaleOption = new(value); } }

        /// <summary>
        /// Used to track the state of WindSpeed
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> WindSpeedOption { get; private set; }

        /// <summary>
        /// 风速 km/h（可选）
        /// </summary>
        /// <value>风速 km/h（可选）</value>
        /* <example>17</example> */
        [JsonPropertyName("wind_speed")]
        public decimal? WindSpeed { get { return this.WindSpeedOption; } set { this.WindSpeedOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetMiscWeather200ResponseHourlyForecastInner {\n");
            sb.Append("  FeelsLike: ").Append(FeelsLike).Append("\n");
            sb.Append("  Humidity: ").Append(Humidity).Append("\n");
            sb.Append("  Pop: ").Append(Pop).Append("\n");
            sb.Append("  Precip: ").Append(Precip).Append("\n");
            sb.Append("  Temperature: ").Append(Temperature).Append("\n");
            sb.Append("  Time: ").Append(Time).Append("\n");
            sb.Append("  UvIndex: ").Append(UvIndex).Append("\n");
            sb.Append("  Visibility: ").Append(Visibility).Append("\n");
            sb.Append("  Weather: ").Append(Weather).Append("\n");
            sb.Append("  WindDirection: ").Append(WindDirection).Append("\n");
            sb.Append("  WindScale: ").Append(WindScale).Append("\n");
            sb.Append("  WindSpeed: ").Append(WindSpeed).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetMiscWeather200ResponseHourlyForecastInner" />
    /// </summary>
    public class GetMiscWeather200ResponseHourlyForecastInnerJsonConverter : JsonConverter<GetMiscWeather200ResponseHourlyForecastInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetMiscWeather200ResponseHourlyForecastInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetMiscWeather200ResponseHourlyForecastInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<decimal?> feelsLike = default;
            Option<decimal?> humidity = default;
            Option<decimal?> pop = default;
            Option<decimal?> precip = default;
            Option<decimal?> temperature = default;
            Option<string?> time = default;
            Option<decimal?> uvIndex = default;
            Option<decimal?> visibility = default;
            Option<string?> weather = default;
            Option<string?> windDirection = default;
            Option<string?> windScale = default;
            Option<decimal?> windSpeed = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "feels_like":
                            feelsLike = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "humidity":
                            humidity = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "pop":
                            pop = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "precip":
                            precip = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "temperature":
                            temperature = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "time":
                            time = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "uv_index":
                            uvIndex = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "visibility":
                            visibility = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "weather":
                            weather = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "wind_direction":
                            windDirection = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "wind_scale":
                            windScale = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "wind_speed":
                            windSpeed = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (feelsLike.IsSet && feelsLike.Value == null)
                throw new ArgumentNullException(nameof(feelsLike), "Property is not nullable for class GetMiscWeather200ResponseHourlyForecastInner.");

            if (humidity.IsSet && humidity.Value == null)
                throw new ArgumentNullException(nameof(humidity), "Property is not nullable for class GetMiscWeather200ResponseHourlyForecastInner.");

            if (pop.IsSet && pop.Value == null)
                throw new ArgumentNullException(nameof(pop), "Property is not nullable for class GetMiscWeather200ResponseHourlyForecastInner.");

            if (precip.IsSet && precip.Value == null)
                throw new ArgumentNullException(nameof(precip), "Property is not nullable for class GetMiscWeather200ResponseHourlyForecastInner.");

            if (temperature.IsSet && temperature.Value == null)
                throw new ArgumentNullException(nameof(temperature), "Property is not nullable for class GetMiscWeather200ResponseHourlyForecastInner.");

            if (time.IsSet && time.Value == null)
                throw new ArgumentNullException(nameof(time), "Property is not nullable for class GetMiscWeather200ResponseHourlyForecastInner.");

            if (uvIndex.IsSet && uvIndex.Value == null)
                throw new ArgumentNullException(nameof(uvIndex), "Property is not nullable for class GetMiscWeather200ResponseHourlyForecastInner.");

            if (visibility.IsSet && visibility.Value == null)
                throw new ArgumentNullException(nameof(visibility), "Property is not nullable for class GetMiscWeather200ResponseHourlyForecastInner.");

            if (weather.IsSet && weather.Value == null)
                throw new ArgumentNullException(nameof(weather), "Property is not nullable for class GetMiscWeather200ResponseHourlyForecastInner.");

            if (windDirection.IsSet && windDirection.Value == null)
                throw new ArgumentNullException(nameof(windDirection), "Property is not nullable for class GetMiscWeather200ResponseHourlyForecastInner.");

            if (windScale.IsSet && windScale.Value == null)
                throw new ArgumentNullException(nameof(windScale), "Property is not nullable for class GetMiscWeather200ResponseHourlyForecastInner.");

            if (windSpeed.IsSet && windSpeed.Value == null)
                throw new ArgumentNullException(nameof(windSpeed), "Property is not nullable for class GetMiscWeather200ResponseHourlyForecastInner.");

            return new GetMiscWeather200ResponseHourlyForecastInner(feelsLike, humidity, pop, precip, temperature, time, uvIndex, visibility, weather, windDirection, windScale, windSpeed);
        }

        /// <summary>
        /// Serializes a <see cref="GetMiscWeather200ResponseHourlyForecastInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getMiscWeather200ResponseHourlyForecastInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetMiscWeather200ResponseHourlyForecastInner getMiscWeather200ResponseHourlyForecastInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getMiscWeather200ResponseHourlyForecastInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetMiscWeather200ResponseHourlyForecastInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getMiscWeather200ResponseHourlyForecastInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetMiscWeather200ResponseHourlyForecastInner getMiscWeather200ResponseHourlyForecastInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getMiscWeather200ResponseHourlyForecastInner.TimeOption.IsSet && getMiscWeather200ResponseHourlyForecastInner.Time == null)
                throw new ArgumentNullException(nameof(getMiscWeather200ResponseHourlyForecastInner.Time), "Property is required for class GetMiscWeather200ResponseHourlyForecastInner.");

            if (getMiscWeather200ResponseHourlyForecastInner.WeatherOption.IsSet && getMiscWeather200ResponseHourlyForecastInner.Weather == null)
                throw new ArgumentNullException(nameof(getMiscWeather200ResponseHourlyForecastInner.Weather), "Property is required for class GetMiscWeather200ResponseHourlyForecastInner.");

            if (getMiscWeather200ResponseHourlyForecastInner.WindDirectionOption.IsSet && getMiscWeather200ResponseHourlyForecastInner.WindDirection == null)
                throw new ArgumentNullException(nameof(getMiscWeather200ResponseHourlyForecastInner.WindDirection), "Property is required for class GetMiscWeather200ResponseHourlyForecastInner.");

            if (getMiscWeather200ResponseHourlyForecastInner.WindScaleOption.IsSet && getMiscWeather200ResponseHourlyForecastInner.WindScale == null)
                throw new ArgumentNullException(nameof(getMiscWeather200ResponseHourlyForecastInner.WindScale), "Property is required for class GetMiscWeather200ResponseHourlyForecastInner.");

            if (getMiscWeather200ResponseHourlyForecastInner.FeelsLikeOption.IsSet)
                writer.WriteNumber("feels_like", getMiscWeather200ResponseHourlyForecastInner.FeelsLikeOption.Value!.Value);

            if (getMiscWeather200ResponseHourlyForecastInner.HumidityOption.IsSet)
                writer.WriteNumber("humidity", getMiscWeather200ResponseHourlyForecastInner.HumidityOption.Value!.Value);

            if (getMiscWeather200ResponseHourlyForecastInner.PopOption.IsSet)
                writer.WriteNumber("pop", getMiscWeather200ResponseHourlyForecastInner.PopOption.Value!.Value);

            if (getMiscWeather200ResponseHourlyForecastInner.PrecipOption.IsSet)
                writer.WriteNumber("precip", getMiscWeather200ResponseHourlyForecastInner.PrecipOption.Value!.Value);

            if (getMiscWeather200ResponseHourlyForecastInner.TemperatureOption.IsSet)
                writer.WriteNumber("temperature", getMiscWeather200ResponseHourlyForecastInner.TemperatureOption.Value!.Value);

            if (getMiscWeather200ResponseHourlyForecastInner.TimeOption.IsSet)
                writer.WriteString("time", getMiscWeather200ResponseHourlyForecastInner.Time);

            if (getMiscWeather200ResponseHourlyForecastInner.UvIndexOption.IsSet)
                writer.WriteNumber("uv_index", getMiscWeather200ResponseHourlyForecastInner.UvIndexOption.Value!.Value);

            if (getMiscWeather200ResponseHourlyForecastInner.VisibilityOption.IsSet)
                writer.WriteNumber("visibility", getMiscWeather200ResponseHourlyForecastInner.VisibilityOption.Value!.Value);

            if (getMiscWeather200ResponseHourlyForecastInner.WeatherOption.IsSet)
                writer.WriteString("weather", getMiscWeather200ResponseHourlyForecastInner.Weather);

            if (getMiscWeather200ResponseHourlyForecastInner.WindDirectionOption.IsSet)
                writer.WriteString("wind_direction", getMiscWeather200ResponseHourlyForecastInner.WindDirection);

            if (getMiscWeather200ResponseHourlyForecastInner.WindScaleOption.IsSet)
                writer.WriteString("wind_scale", getMiscWeather200ResponseHourlyForecastInner.WindScale);

            if (getMiscWeather200ResponseHourlyForecastInner.WindSpeedOption.IsSet)
                writer.WriteNumber("wind_speed", getMiscWeather200ResponseHourlyForecastInner.WindSpeedOption.Value!.Value);
        }
    }
}
