// <auto-generated>
/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using uapi-sdk-csharp.Client;

namespace uapi-sdk-csharp.Model
{
    /// <summary>
    /// GetMiscWeather200ResponseForecastInner
    /// </summary>
    public partial class GetMiscWeather200ResponseForecastInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetMiscWeather200ResponseForecastInner" /> class.
        /// </summary>
        /// <param name="date">日期 YYYY-MM-DD</param>
        /// <param name="week">星期几（&#x60;lang&#x3D;en&#x60; 时返回英文星期）</param>
        /// <param name="tempMax">最高温度 °C</param>
        /// <param name="tempMin">最低温度 °C</param>
        /// <param name="weatherDay">白天天气（&#x60;lang&#x3D;en&#x60; 时返回英文）</param>
        /// <param name="weatherNight">夜间天气（&#x60;lang&#x3D;en&#x60; 时返回英文）</param>
        /// <param name="windDirDay">白天风向（可选，&#x60;lang&#x3D;en&#x60; 时返回英文）</param>
        /// <param name="windDirNight">夜间风向（可选，&#x60;lang&#x3D;en&#x60; 时返回英文）</param>
        /// <param name="windScaleDay">白天风力（可选，&#x60;lang&#x3D;en&#x60; 时返回英文）</param>
        /// <param name="windScaleNight">夜间风力（可选，&#x60;lang&#x3D;en&#x60; 时返回英文）</param>
        /// <param name="windSpeedDay">白天风速 km/h（可选）</param>
        /// <param name="humidity">湿度 %（可选）</param>
        /// <param name="precip">降水量 mm（可选）</param>
        /// <param name="visibility">能见度 km（可选）</param>
        /// <param name="uvIndex">紫外线指数（可选）</param>
        /// <param name="sunrise">日出时间 HH:MM（可选）</param>
        /// <param name="sunset">日落时间 HH:MM（可选）</param>
        [JsonConstructor]
        public GetMiscWeather200ResponseForecastInner(Option<string?> date = default, Option<string?> week = default, Option<decimal?> tempMax = default, Option<decimal?> tempMin = default, Option<string?> weatherDay = default, Option<string?> weatherNight = default, Option<string?> windDirDay = default, Option<string?> windDirNight = default, Option<string?> windScaleDay = default, Option<string?> windScaleNight = default, Option<decimal?> windSpeedDay = default, Option<decimal?> humidity = default, Option<decimal?> precip = default, Option<decimal?> visibility = default, Option<decimal?> uvIndex = default, Option<string?> sunrise = default, Option<string?> sunset = default)
        {
            DateOption = date;
            WeekOption = week;
            TempMaxOption = tempMax;
            TempMinOption = tempMin;
            WeatherDayOption = weatherDay;
            WeatherNightOption = weatherNight;
            WindDirDayOption = windDirDay;
            WindDirNightOption = windDirNight;
            WindScaleDayOption = windScaleDay;
            WindScaleNightOption = windScaleNight;
            WindSpeedDayOption = windSpeedDay;
            HumidityOption = humidity;
            PrecipOption = precip;
            VisibilityOption = visibility;
            UvIndexOption = uvIndex;
            SunriseOption = sunrise;
            SunsetOption = sunset;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Date
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DateOption { get; private set; }

        /// <summary>
        /// 日期 YYYY-MM-DD
        /// </summary>
        /// <value>日期 YYYY-MM-DD</value>
        /* <example>2026-02-19</example> */
        [JsonPropertyName("date")]
        public string? Date { get { return this.DateOption; } set { this.DateOption = new(value); } }

        /// <summary>
        /// Used to track the state of Week
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> WeekOption { get; private set; }

        /// <summary>
        /// 星期几（&#x60;lang&#x3D;en&#x60; 时返回英文星期）
        /// </summary>
        /// <value>星期几（&#x60;lang&#x3D;en&#x60; 时返回英文星期）</value>
        /* <example>星期四</example> */
        [JsonPropertyName("week")]
        public string? Week { get { return this.WeekOption; } set { this.WeekOption = new(value); } }

        /// <summary>
        /// Used to track the state of TempMax
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> TempMaxOption { get; private set; }

        /// <summary>
        /// 最高温度 °C
        /// </summary>
        /// <value>最高温度 °C</value>
        /* <example>14</example> */
        [JsonPropertyName("temp_max")]
        public decimal? TempMax { get { return this.TempMaxOption; } set { this.TempMaxOption = new(value); } }

        /// <summary>
        /// Used to track the state of TempMin
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> TempMinOption { get; private set; }

        /// <summary>
        /// 最低温度 °C
        /// </summary>
        /// <value>最低温度 °C</value>
        /* <example>-1</example> */
        [JsonPropertyName("temp_min")]
        public decimal? TempMin { get { return this.TempMinOption; } set { this.TempMinOption = new(value); } }

        /// <summary>
        /// Used to track the state of WeatherDay
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> WeatherDayOption { get; private set; }

        /// <summary>
        /// 白天天气（&#x60;lang&#x3D;en&#x60; 时返回英文）
        /// </summary>
        /// <value>白天天气（&#x60;lang&#x3D;en&#x60; 时返回英文）</value>
        /* <example>晴</example> */
        [JsonPropertyName("weather_day")]
        public string? WeatherDay { get { return this.WeatherDayOption; } set { this.WeatherDayOption = new(value); } }

        /// <summary>
        /// Used to track the state of WeatherNight
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> WeatherNightOption { get; private set; }

        /// <summary>
        /// 夜间天气（&#x60;lang&#x3D;en&#x60; 时返回英文）
        /// </summary>
        /// <value>夜间天气（&#x60;lang&#x3D;en&#x60; 时返回英文）</value>
        /* <example>晴</example> */
        [JsonPropertyName("weather_night")]
        public string? WeatherNight { get { return this.WeatherNightOption; } set { this.WeatherNightOption = new(value); } }

        /// <summary>
        /// Used to track the state of WindDirDay
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> WindDirDayOption { get; private set; }

        /// <summary>
        /// 白天风向（可选，&#x60;lang&#x3D;en&#x60; 时返回英文）
        /// </summary>
        /// <value>白天风向（可选，&#x60;lang&#x3D;en&#x60; 时返回英文）</value>
        /* <example>西南风</example> */
        [JsonPropertyName("wind_dir_day")]
        public string? WindDirDay { get { return this.WindDirDayOption; } set { this.WindDirDayOption = new(value); } }

        /// <summary>
        /// Used to track the state of WindDirNight
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> WindDirNightOption { get; private set; }

        /// <summary>
        /// 夜间风向（可选，&#x60;lang&#x3D;en&#x60; 时返回英文）
        /// </summary>
        /// <value>夜间风向（可选，&#x60;lang&#x3D;en&#x60; 时返回英文）</value>
        /* <example>北风</example> */
        [JsonPropertyName("wind_dir_night")]
        public string? WindDirNight { get { return this.WindDirNightOption; } set { this.WindDirNightOption = new(value); } }

        /// <summary>
        /// Used to track the state of WindScaleDay
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> WindScaleDayOption { get; private set; }

        /// <summary>
        /// 白天风力（可选，&#x60;lang&#x3D;en&#x60; 时返回英文）
        /// </summary>
        /// <value>白天风力（可选，&#x60;lang&#x3D;en&#x60; 时返回英文）</value>
        /* <example>微风</example> */
        [JsonPropertyName("wind_scale_day")]
        public string? WindScaleDay { get { return this.WindScaleDayOption; } set { this.WindScaleDayOption = new(value); } }

        /// <summary>
        /// Used to track the state of WindScaleNight
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> WindScaleNightOption { get; private set; }

        /// <summary>
        /// 夜间风力（可选，&#x60;lang&#x3D;en&#x60; 时返回英文）
        /// </summary>
        /// <value>夜间风力（可选，&#x60;lang&#x3D;en&#x60; 时返回英文）</value>
        /* <example>微风</example> */
        [JsonPropertyName("wind_scale_night")]
        public string? WindScaleNight { get { return this.WindScaleNightOption; } set { this.WindScaleNightOption = new(value); } }

        /// <summary>
        /// Used to track the state of WindSpeedDay
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> WindSpeedDayOption { get; private set; }

        /// <summary>
        /// 白天风速 km/h（可选）
        /// </summary>
        /// <value>白天风速 km/h（可选）</value>
        /* <example>17</example> */
        [JsonPropertyName("wind_speed_day")]
        public decimal? WindSpeedDay { get { return this.WindSpeedDayOption; } set { this.WindSpeedDayOption = new(value); } }

        /// <summary>
        /// Used to track the state of Humidity
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> HumidityOption { get; private set; }

        /// <summary>
        /// 湿度 %（可选）
        /// </summary>
        /// <value>湿度 %（可选）</value>
        /* <example>40</example> */
        [JsonPropertyName("humidity")]
        public decimal? Humidity { get { return this.HumidityOption; } set { this.HumidityOption = new(value); } }

        /// <summary>
        /// Used to track the state of Precip
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> PrecipOption { get; private set; }

        /// <summary>
        /// 降水量 mm（可选）
        /// </summary>
        /// <value>降水量 mm（可选）</value>
        /* <example>0</example> */
        [JsonPropertyName("precip")]
        public decimal? Precip { get { return this.PrecipOption; } set { this.PrecipOption = new(value); } }

        /// <summary>
        /// Used to track the state of Visibility
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> VisibilityOption { get; private set; }

        /// <summary>
        /// 能见度 km（可选）
        /// </summary>
        /// <value>能见度 km（可选）</value>
        /* <example>25</example> */
        [JsonPropertyName("visibility")]
        public decimal? Visibility { get { return this.VisibilityOption; } set { this.VisibilityOption = new(value); } }

        /// <summary>
        /// Used to track the state of UvIndex
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> UvIndexOption { get; private set; }

        /// <summary>
        /// 紫外线指数（可选）
        /// </summary>
        /// <value>紫外线指数（可选）</value>
        /* <example>5</example> */
        [JsonPropertyName("uv_index")]
        public decimal? UvIndex { get { return this.UvIndexOption; } set { this.UvIndexOption = new(value); } }

        /// <summary>
        /// Used to track the state of Sunrise
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SunriseOption { get; private set; }

        /// <summary>
        /// 日出时间 HH:MM（可选）
        /// </summary>
        /// <value>日出时间 HH:MM（可选）</value>
        /* <example>06:52</example> */
        [JsonPropertyName("sunrise")]
        public string? Sunrise { get { return this.SunriseOption; } set { this.SunriseOption = new(value); } }

        /// <summary>
        /// Used to track the state of Sunset
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SunsetOption { get; private set; }

        /// <summary>
        /// 日落时间 HH:MM（可选）
        /// </summary>
        /// <value>日落时间 HH:MM（可选）</value>
        /* <example>17:56</example> */
        [JsonPropertyName("sunset")]
        public string? Sunset { get { return this.SunsetOption; } set { this.SunsetOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetMiscWeather200ResponseForecastInner {\n");
            sb.Append("  Date: ").Append(Date).Append("\n");
            sb.Append("  Week: ").Append(Week).Append("\n");
            sb.Append("  TempMax: ").Append(TempMax).Append("\n");
            sb.Append("  TempMin: ").Append(TempMin).Append("\n");
            sb.Append("  WeatherDay: ").Append(WeatherDay).Append("\n");
            sb.Append("  WeatherNight: ").Append(WeatherNight).Append("\n");
            sb.Append("  WindDirDay: ").Append(WindDirDay).Append("\n");
            sb.Append("  WindDirNight: ").Append(WindDirNight).Append("\n");
            sb.Append("  WindScaleDay: ").Append(WindScaleDay).Append("\n");
            sb.Append("  WindScaleNight: ").Append(WindScaleNight).Append("\n");
            sb.Append("  WindSpeedDay: ").Append(WindSpeedDay).Append("\n");
            sb.Append("  Humidity: ").Append(Humidity).Append("\n");
            sb.Append("  Precip: ").Append(Precip).Append("\n");
            sb.Append("  Visibility: ").Append(Visibility).Append("\n");
            sb.Append("  UvIndex: ").Append(UvIndex).Append("\n");
            sb.Append("  Sunrise: ").Append(Sunrise).Append("\n");
            sb.Append("  Sunset: ").Append(Sunset).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetMiscWeather200ResponseForecastInner" />
    /// </summary>
    public class GetMiscWeather200ResponseForecastInnerJsonConverter : JsonConverter<GetMiscWeather200ResponseForecastInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetMiscWeather200ResponseForecastInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetMiscWeather200ResponseForecastInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> date = default;
            Option<string?> week = default;
            Option<decimal?> tempMax = default;
            Option<decimal?> tempMin = default;
            Option<string?> weatherDay = default;
            Option<string?> weatherNight = default;
            Option<string?> windDirDay = default;
            Option<string?> windDirNight = default;
            Option<string?> windScaleDay = default;
            Option<string?> windScaleNight = default;
            Option<decimal?> windSpeedDay = default;
            Option<decimal?> humidity = default;
            Option<decimal?> precip = default;
            Option<decimal?> visibility = default;
            Option<decimal?> uvIndex = default;
            Option<string?> sunrise = default;
            Option<string?> sunset = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "date":
                            date = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "week":
                            week = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "temp_max":
                            tempMax = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "temp_min":
                            tempMin = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "weather_day":
                            weatherDay = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "weather_night":
                            weatherNight = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "wind_dir_day":
                            windDirDay = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "wind_dir_night":
                            windDirNight = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "wind_scale_day":
                            windScaleDay = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "wind_scale_night":
                            windScaleNight = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "wind_speed_day":
                            windSpeedDay = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "humidity":
                            humidity = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "precip":
                            precip = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "visibility":
                            visibility = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "uv_index":
                            uvIndex = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "sunrise":
                            sunrise = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "sunset":
                            sunset = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (date.IsSet && date.Value == null)
                throw new ArgumentNullException(nameof(date), "Property is not nullable for class GetMiscWeather200ResponseForecastInner.");

            if (week.IsSet && week.Value == null)
                throw new ArgumentNullException(nameof(week), "Property is not nullable for class GetMiscWeather200ResponseForecastInner.");

            if (tempMax.IsSet && tempMax.Value == null)
                throw new ArgumentNullException(nameof(tempMax), "Property is not nullable for class GetMiscWeather200ResponseForecastInner.");

            if (tempMin.IsSet && tempMin.Value == null)
                throw new ArgumentNullException(nameof(tempMin), "Property is not nullable for class GetMiscWeather200ResponseForecastInner.");

            if (weatherDay.IsSet && weatherDay.Value == null)
                throw new ArgumentNullException(nameof(weatherDay), "Property is not nullable for class GetMiscWeather200ResponseForecastInner.");

            if (weatherNight.IsSet && weatherNight.Value == null)
                throw new ArgumentNullException(nameof(weatherNight), "Property is not nullable for class GetMiscWeather200ResponseForecastInner.");

            if (windDirDay.IsSet && windDirDay.Value == null)
                throw new ArgumentNullException(nameof(windDirDay), "Property is not nullable for class GetMiscWeather200ResponseForecastInner.");

            if (windDirNight.IsSet && windDirNight.Value == null)
                throw new ArgumentNullException(nameof(windDirNight), "Property is not nullable for class GetMiscWeather200ResponseForecastInner.");

            if (windScaleDay.IsSet && windScaleDay.Value == null)
                throw new ArgumentNullException(nameof(windScaleDay), "Property is not nullable for class GetMiscWeather200ResponseForecastInner.");

            if (windScaleNight.IsSet && windScaleNight.Value == null)
                throw new ArgumentNullException(nameof(windScaleNight), "Property is not nullable for class GetMiscWeather200ResponseForecastInner.");

            if (windSpeedDay.IsSet && windSpeedDay.Value == null)
                throw new ArgumentNullException(nameof(windSpeedDay), "Property is not nullable for class GetMiscWeather200ResponseForecastInner.");

            if (humidity.IsSet && humidity.Value == null)
                throw new ArgumentNullException(nameof(humidity), "Property is not nullable for class GetMiscWeather200ResponseForecastInner.");

            if (precip.IsSet && precip.Value == null)
                throw new ArgumentNullException(nameof(precip), "Property is not nullable for class GetMiscWeather200ResponseForecastInner.");

            if (visibility.IsSet && visibility.Value == null)
                throw new ArgumentNullException(nameof(visibility), "Property is not nullable for class GetMiscWeather200ResponseForecastInner.");

            if (uvIndex.IsSet && uvIndex.Value == null)
                throw new ArgumentNullException(nameof(uvIndex), "Property is not nullable for class GetMiscWeather200ResponseForecastInner.");

            if (sunrise.IsSet && sunrise.Value == null)
                throw new ArgumentNullException(nameof(sunrise), "Property is not nullable for class GetMiscWeather200ResponseForecastInner.");

            if (sunset.IsSet && sunset.Value == null)
                throw new ArgumentNullException(nameof(sunset), "Property is not nullable for class GetMiscWeather200ResponseForecastInner.");

            return new GetMiscWeather200ResponseForecastInner(date, week, tempMax, tempMin, weatherDay, weatherNight, windDirDay, windDirNight, windScaleDay, windScaleNight, windSpeedDay, humidity, precip, visibility, uvIndex, sunrise, sunset);
        }

        /// <summary>
        /// Serializes a <see cref="GetMiscWeather200ResponseForecastInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getMiscWeather200ResponseForecastInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetMiscWeather200ResponseForecastInner getMiscWeather200ResponseForecastInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getMiscWeather200ResponseForecastInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetMiscWeather200ResponseForecastInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getMiscWeather200ResponseForecastInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetMiscWeather200ResponseForecastInner getMiscWeather200ResponseForecastInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getMiscWeather200ResponseForecastInner.DateOption.IsSet && getMiscWeather200ResponseForecastInner.Date == null)
                throw new ArgumentNullException(nameof(getMiscWeather200ResponseForecastInner.Date), "Property is required for class GetMiscWeather200ResponseForecastInner.");

            if (getMiscWeather200ResponseForecastInner.WeekOption.IsSet && getMiscWeather200ResponseForecastInner.Week == null)
                throw new ArgumentNullException(nameof(getMiscWeather200ResponseForecastInner.Week), "Property is required for class GetMiscWeather200ResponseForecastInner.");

            if (getMiscWeather200ResponseForecastInner.WeatherDayOption.IsSet && getMiscWeather200ResponseForecastInner.WeatherDay == null)
                throw new ArgumentNullException(nameof(getMiscWeather200ResponseForecastInner.WeatherDay), "Property is required for class GetMiscWeather200ResponseForecastInner.");

            if (getMiscWeather200ResponseForecastInner.WeatherNightOption.IsSet && getMiscWeather200ResponseForecastInner.WeatherNight == null)
                throw new ArgumentNullException(nameof(getMiscWeather200ResponseForecastInner.WeatherNight), "Property is required for class GetMiscWeather200ResponseForecastInner.");

            if (getMiscWeather200ResponseForecastInner.WindDirDayOption.IsSet && getMiscWeather200ResponseForecastInner.WindDirDay == null)
                throw new ArgumentNullException(nameof(getMiscWeather200ResponseForecastInner.WindDirDay), "Property is required for class GetMiscWeather200ResponseForecastInner.");

            if (getMiscWeather200ResponseForecastInner.WindDirNightOption.IsSet && getMiscWeather200ResponseForecastInner.WindDirNight == null)
                throw new ArgumentNullException(nameof(getMiscWeather200ResponseForecastInner.WindDirNight), "Property is required for class GetMiscWeather200ResponseForecastInner.");

            if (getMiscWeather200ResponseForecastInner.WindScaleDayOption.IsSet && getMiscWeather200ResponseForecastInner.WindScaleDay == null)
                throw new ArgumentNullException(nameof(getMiscWeather200ResponseForecastInner.WindScaleDay), "Property is required for class GetMiscWeather200ResponseForecastInner.");

            if (getMiscWeather200ResponseForecastInner.WindScaleNightOption.IsSet && getMiscWeather200ResponseForecastInner.WindScaleNight == null)
                throw new ArgumentNullException(nameof(getMiscWeather200ResponseForecastInner.WindScaleNight), "Property is required for class GetMiscWeather200ResponseForecastInner.");

            if (getMiscWeather200ResponseForecastInner.SunriseOption.IsSet && getMiscWeather200ResponseForecastInner.Sunrise == null)
                throw new ArgumentNullException(nameof(getMiscWeather200ResponseForecastInner.Sunrise), "Property is required for class GetMiscWeather200ResponseForecastInner.");

            if (getMiscWeather200ResponseForecastInner.SunsetOption.IsSet && getMiscWeather200ResponseForecastInner.Sunset == null)
                throw new ArgumentNullException(nameof(getMiscWeather200ResponseForecastInner.Sunset), "Property is required for class GetMiscWeather200ResponseForecastInner.");

            if (getMiscWeather200ResponseForecastInner.DateOption.IsSet)
                writer.WriteString("date", getMiscWeather200ResponseForecastInner.Date);

            if (getMiscWeather200ResponseForecastInner.WeekOption.IsSet)
                writer.WriteString("week", getMiscWeather200ResponseForecastInner.Week);

            if (getMiscWeather200ResponseForecastInner.TempMaxOption.IsSet)
                writer.WriteNumber("temp_max", getMiscWeather200ResponseForecastInner.TempMaxOption.Value!.Value);

            if (getMiscWeather200ResponseForecastInner.TempMinOption.IsSet)
                writer.WriteNumber("temp_min", getMiscWeather200ResponseForecastInner.TempMinOption.Value!.Value);

            if (getMiscWeather200ResponseForecastInner.WeatherDayOption.IsSet)
                writer.WriteString("weather_day", getMiscWeather200ResponseForecastInner.WeatherDay);

            if (getMiscWeather200ResponseForecastInner.WeatherNightOption.IsSet)
                writer.WriteString("weather_night", getMiscWeather200ResponseForecastInner.WeatherNight);

            if (getMiscWeather200ResponseForecastInner.WindDirDayOption.IsSet)
                writer.WriteString("wind_dir_day", getMiscWeather200ResponseForecastInner.WindDirDay);

            if (getMiscWeather200ResponseForecastInner.WindDirNightOption.IsSet)
                writer.WriteString("wind_dir_night", getMiscWeather200ResponseForecastInner.WindDirNight);

            if (getMiscWeather200ResponseForecastInner.WindScaleDayOption.IsSet)
                writer.WriteString("wind_scale_day", getMiscWeather200ResponseForecastInner.WindScaleDay);

            if (getMiscWeather200ResponseForecastInner.WindScaleNightOption.IsSet)
                writer.WriteString("wind_scale_night", getMiscWeather200ResponseForecastInner.WindScaleNight);

            if (getMiscWeather200ResponseForecastInner.WindSpeedDayOption.IsSet)
                writer.WriteNumber("wind_speed_day", getMiscWeather200ResponseForecastInner.WindSpeedDayOption.Value!.Value);

            if (getMiscWeather200ResponseForecastInner.HumidityOption.IsSet)
                writer.WriteNumber("humidity", getMiscWeather200ResponseForecastInner.HumidityOption.Value!.Value);

            if (getMiscWeather200ResponseForecastInner.PrecipOption.IsSet)
                writer.WriteNumber("precip", getMiscWeather200ResponseForecastInner.PrecipOption.Value!.Value);

            if (getMiscWeather200ResponseForecastInner.VisibilityOption.IsSet)
                writer.WriteNumber("visibility", getMiscWeather200ResponseForecastInner.VisibilityOption.Value!.Value);

            if (getMiscWeather200ResponseForecastInner.UvIndexOption.IsSet)
                writer.WriteNumber("uv_index", getMiscWeather200ResponseForecastInner.UvIndexOption.Value!.Value);

            if (getMiscWeather200ResponseForecastInner.SunriseOption.IsSet)
                writer.WriteString("sunrise", getMiscWeather200ResponseForecastInner.Sunrise);

            if (getMiscWeather200ResponseForecastInner.SunsetOption.IsSet)
                writer.WriteString("sunset", getMiscWeather200ResponseForecastInner.Sunset);
        }
    }
}
