// <auto-generated>
/*
 * UAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using uapi-sdk-csharp.Client;

namespace uapi-sdk-csharp.Model
{
    /// <summary>
    /// GetMiscHotboard200ResponseOneOf1ResultsInner
    /// </summary>
    public partial class GetMiscHotboard200ResponseOneOf1ResultsInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetMiscHotboard200ResponseOneOf1ResultsInner" /> class.
        /// </summary>
        /// <param name="title">title</param>
        /// <param name="hotValue">hotValue</param>
        /// <param name="url">url</param>
        [JsonConstructor]
        public GetMiscHotboard200ResponseOneOf1ResultsInner(Option<string?> title = default, Option<string?> hotValue = default, Option<string?> url = default)
        {
            TitleOption = title;
            HotValueOption = hotValue;
            UrlOption = url;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Title
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TitleOption { get; private set; }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        /* <example>AI技术突破</example> */
        [JsonPropertyName("title")]
        public string? Title { get { return this.TitleOption; } set { this.TitleOption = new(value); } }

        /// <summary>
        /// Used to track the state of HotValue
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> HotValueOption { get; private set; }

        /// <summary>
        /// Gets or Sets HotValue
        /// </summary>
        /* <example>999999</example> */
        [JsonPropertyName("hot_value")]
        public string? HotValue { get { return this.HotValueOption; } set { this.HotValueOption = new(value); } }

        /// <summary>
        /// Used to track the state of Url
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UrlOption { get; private set; }

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        /* <example>https://example.com</example> */
        [JsonPropertyName("url")]
        public string? Url { get { return this.UrlOption; } set { this.UrlOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetMiscHotboard200ResponseOneOf1ResultsInner {\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  HotValue: ").Append(HotValue).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetMiscHotboard200ResponseOneOf1ResultsInner" />
    /// </summary>
    public class GetMiscHotboard200ResponseOneOf1ResultsInnerJsonConverter : JsonConverter<GetMiscHotboard200ResponseOneOf1ResultsInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetMiscHotboard200ResponseOneOf1ResultsInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetMiscHotboard200ResponseOneOf1ResultsInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> title = default;
            Option<string?> hotValue = default;
            Option<string?> url = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "title":
                            title = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "hot_value":
                            hotValue = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "url":
                            url = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (title.IsSet && title.Value == null)
                throw new ArgumentNullException(nameof(title), "Property is not nullable for class GetMiscHotboard200ResponseOneOf1ResultsInner.");

            if (hotValue.IsSet && hotValue.Value == null)
                throw new ArgumentNullException(nameof(hotValue), "Property is not nullable for class GetMiscHotboard200ResponseOneOf1ResultsInner.");

            if (url.IsSet && url.Value == null)
                throw new ArgumentNullException(nameof(url), "Property is not nullable for class GetMiscHotboard200ResponseOneOf1ResultsInner.");

            return new GetMiscHotboard200ResponseOneOf1ResultsInner(title, hotValue, url);
        }

        /// <summary>
        /// Serializes a <see cref="GetMiscHotboard200ResponseOneOf1ResultsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getMiscHotboard200ResponseOneOf1ResultsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetMiscHotboard200ResponseOneOf1ResultsInner getMiscHotboard200ResponseOneOf1ResultsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getMiscHotboard200ResponseOneOf1ResultsInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetMiscHotboard200ResponseOneOf1ResultsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getMiscHotboard200ResponseOneOf1ResultsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetMiscHotboard200ResponseOneOf1ResultsInner getMiscHotboard200ResponseOneOf1ResultsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getMiscHotboard200ResponseOneOf1ResultsInner.TitleOption.IsSet && getMiscHotboard200ResponseOneOf1ResultsInner.Title == null)
                throw new ArgumentNullException(nameof(getMiscHotboard200ResponseOneOf1ResultsInner.Title), "Property is required for class GetMiscHotboard200ResponseOneOf1ResultsInner.");

            if (getMiscHotboard200ResponseOneOf1ResultsInner.HotValueOption.IsSet && getMiscHotboard200ResponseOneOf1ResultsInner.HotValue == null)
                throw new ArgumentNullException(nameof(getMiscHotboard200ResponseOneOf1ResultsInner.HotValue), "Property is required for class GetMiscHotboard200ResponseOneOf1ResultsInner.");

            if (getMiscHotboard200ResponseOneOf1ResultsInner.UrlOption.IsSet && getMiscHotboard200ResponseOneOf1ResultsInner.Url == null)
                throw new ArgumentNullException(nameof(getMiscHotboard200ResponseOneOf1ResultsInner.Url), "Property is required for class GetMiscHotboard200ResponseOneOf1ResultsInner.");

            if (getMiscHotboard200ResponseOneOf1ResultsInner.TitleOption.IsSet)
                writer.WriteString("title", getMiscHotboard200ResponseOneOf1ResultsInner.Title);

            if (getMiscHotboard200ResponseOneOf1ResultsInner.HotValueOption.IsSet)
                writer.WriteString("hot_value", getMiscHotboard200ResponseOneOf1ResultsInner.HotValue);

            if (getMiscHotboard200ResponseOneOf1ResultsInner.UrlOption.IsSet)
                writer.WriteString("url", getMiscHotboard200ResponseOneOf1ResultsInner.Url);
        }
    }
}
