// <auto-generated>
/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using uapi-sdk-csharp.Client;

namespace uapi-sdk-csharp.Model
{
    /// <summary>
    /// GetNetworkWhois404Response
    /// </summary>
    public partial class GetNetworkWhois404Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetNetworkWhois404Response" /> class.
        /// </summary>
        /// <param name="code">code</param>
        /// <param name="details">details</param>
        /// <param name="message">message</param>
        [JsonConstructor]
        public GetNetworkWhois404Response(Option<string?> code = default, Option<Object?> details = default, Option<string?> message = default)
        {
            CodeOption = code;
            DetailsOption = details;
            MessageOption = message;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Code
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CodeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Code
        /// </summary>
        /* <example>NOT_FOUND</example> */
        [JsonPropertyName("code")]
        public string? Code { get { return this.CodeOption; } set { this.CodeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Details
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> DetailsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Details
        /// </summary>
        [JsonPropertyName("details")]
        public Object? Details { get { return this.DetailsOption; } set { this.DetailsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Message
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MessageOption { get; private set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        /* <example>WHOIS information not found for the domain.</example> */
        [JsonPropertyName("message")]
        public string? Message { get { return this.MessageOption; } set { this.MessageOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetNetworkWhois404Response {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Details: ").Append(Details).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetNetworkWhois404Response" />
    /// </summary>
    public class GetNetworkWhois404ResponseJsonConverter : JsonConverter<GetNetworkWhois404Response>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetNetworkWhois404Response" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetNetworkWhois404Response Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> code = default;
            Option<Object?> details = default;
            Option<string?> message = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "code":
                            code = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "details":
                            details = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "message":
                            message = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (code.IsSet && code.Value == null)
                throw new ArgumentNullException(nameof(code), "Property is not nullable for class GetNetworkWhois404Response.");

            if (details.IsSet && details.Value == null)
                throw new ArgumentNullException(nameof(details), "Property is not nullable for class GetNetworkWhois404Response.");

            if (message.IsSet && message.Value == null)
                throw new ArgumentNullException(nameof(message), "Property is not nullable for class GetNetworkWhois404Response.");

            return new GetNetworkWhois404Response(code, details, message);
        }

        /// <summary>
        /// Serializes a <see cref="GetNetworkWhois404Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getNetworkWhois404Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetNetworkWhois404Response getNetworkWhois404Response, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getNetworkWhois404Response, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetNetworkWhois404Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getNetworkWhois404Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetNetworkWhois404Response getNetworkWhois404Response, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getNetworkWhois404Response.CodeOption.IsSet && getNetworkWhois404Response.Code == null)
                throw new ArgumentNullException(nameof(getNetworkWhois404Response.Code), "Property is required for class GetNetworkWhois404Response.");

            if (getNetworkWhois404Response.DetailsOption.IsSet && getNetworkWhois404Response.Details == null)
                throw new ArgumentNullException(nameof(getNetworkWhois404Response.Details), "Property is required for class GetNetworkWhois404Response.");

            if (getNetworkWhois404Response.MessageOption.IsSet && getNetworkWhois404Response.Message == null)
                throw new ArgumentNullException(nameof(getNetworkWhois404Response.Message), "Property is required for class GetNetworkWhois404Response.");

            if (getNetworkWhois404Response.CodeOption.IsSet)
                writer.WriteString("code", getNetworkWhois404Response.Code);

            if (getNetworkWhois404Response.DetailsOption.IsSet)
            {
                writer.WritePropertyName("details");
                JsonSerializer.Serialize(writer, getNetworkWhois404Response.Details, jsonSerializerOptions);
            }
            if (getNetworkWhois404Response.MessageOption.IsSet)
                writer.WriteString("message", getNetworkWhois404Response.Message);
        }
    }
}
