// <auto-generated>
/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using uapi-sdk-csharp.Client;

namespace uapi-sdk-csharp.Model
{
    /// <summary>
    /// 查询指定path参数时返回的单个端点统计数据
    /// </summary>
    public partial class GetStatusUsage200ResponseAnyOf1 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetStatusUsage200ResponseAnyOf1" /> class.
        /// </summary>
        /// <param name="path">path</param>
        /// <param name="count">count</param>
        [JsonConstructor]
        public GetStatusUsage200ResponseAnyOf1(Option<string?> path = default, Option<int?> count = default)
        {
            PathOption = path;
            CountOption = count;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Path
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PathOption { get; private set; }

        /// <summary>
        /// Gets or Sets Path
        /// </summary>
        /* <example>/api/v1/image/motou</example> */
        [JsonPropertyName("path")]
        public string? Path { get { return this.PathOption; } set { this.PathOption = new(value); } }

        /// <summary>
        /// Used to track the state of Count
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> CountOption { get; private set; }

        /// <summary>
        /// Gets or Sets Count
        /// </summary>
        /* <example>22310</example> */
        [JsonPropertyName("count")]
        public int? Count { get { return this.CountOption; } set { this.CountOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetStatusUsage200ResponseAnyOf1 {\n");
            sb.Append("  Path: ").Append(Path).Append("\n");
            sb.Append("  Count: ").Append(Count).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetStatusUsage200ResponseAnyOf1" />
    /// </summary>
    public class GetStatusUsage200ResponseAnyOf1JsonConverter : JsonConverter<GetStatusUsage200ResponseAnyOf1>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetStatusUsage200ResponseAnyOf1" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetStatusUsage200ResponseAnyOf1 Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> path = default;
            Option<int?> count = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "path":
                            path = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "count":
                            count = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (path.IsSet && path.Value == null)
                throw new ArgumentNullException(nameof(path), "Property is not nullable for class GetStatusUsage200ResponseAnyOf1.");

            if (count.IsSet && count.Value == null)
                throw new ArgumentNullException(nameof(count), "Property is not nullable for class GetStatusUsage200ResponseAnyOf1.");

            return new GetStatusUsage200ResponseAnyOf1(path, count);
        }

        /// <summary>
        /// Serializes a <see cref="GetStatusUsage200ResponseAnyOf1" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getStatusUsage200ResponseAnyOf1"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetStatusUsage200ResponseAnyOf1 getStatusUsage200ResponseAnyOf1, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getStatusUsage200ResponseAnyOf1, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetStatusUsage200ResponseAnyOf1" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getStatusUsage200ResponseAnyOf1"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetStatusUsage200ResponseAnyOf1 getStatusUsage200ResponseAnyOf1, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getStatusUsage200ResponseAnyOf1.PathOption.IsSet && getStatusUsage200ResponseAnyOf1.Path == null)
                throw new ArgumentNullException(nameof(getStatusUsage200ResponseAnyOf1.Path), "Property is required for class GetStatusUsage200ResponseAnyOf1.");

            if (getStatusUsage200ResponseAnyOf1.PathOption.IsSet)
                writer.WriteString("path", getStatusUsage200ResponseAnyOf1.Path);

            if (getStatusUsage200ResponseAnyOf1.CountOption.IsSet)
                writer.WriteNumber("count", getStatusUsage200ResponseAnyOf1.CountOption.Value!.Value);
        }
    }
}
