// <auto-generated>
/*
 * UAPI OpenAPI
 *
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using uapi-sdk-csharp.Client;

namespace uapi-sdk-csharp.Model
{
    /// <summary>
    /// GetSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner
    /// </summary>
    public partial class GetSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner" /> class.
        /// </summary>
        /// <param name="aid">关联 AV 号。</param>
        /// <param name="desc">荣誉名称。</param>
        /// <param name="type">荣誉类型。</param>
        /// <param name="weeklyRecommendNum">周推荐序号。</param>
        [JsonConstructor]
        public GetSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner(Option<decimal?> aid = default, Option<string?> desc = default, Option<decimal?> type = default, Option<decimal?> weeklyRecommendNum = default)
        {
            AidOption = aid;
            DescOption = desc;
            TypeOption = type;
            WeeklyRecommendNumOption = weeklyRecommendNum;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Aid
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> AidOption { get; private set; }

        /// <summary>
        /// 关联 AV 号。
        /// </summary>
        /// <value>关联 AV 号。</value>
        /* <example>75836761</example> */
        [JsonPropertyName("aid")]
        public decimal? Aid { get { return this.AidOption; } set { this.AidOption = new(value); } }

        /// <summary>
        /// Used to track the state of Desc
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescOption { get; private set; }

        /// <summary>
        /// 荣誉名称。
        /// </summary>
        /// <value>荣誉名称。</value>
        /* <example>每周必看</example> */
        [JsonPropertyName("desc")]
        public string? Desc { get { return this.DescOption; } set { this.DescOption = new(value); } }

        /// <summary>
        /// Used to track the state of Type
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> TypeOption { get; private set; }

        /// <summary>
        /// 荣誉类型。
        /// </summary>
        /// <value>荣誉类型。</value>
        /* <example>1</example> */
        [JsonPropertyName("type")]
        public decimal? Type { get { return this.TypeOption; } set { this.TypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of WeeklyRecommendNum
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> WeeklyRecommendNumOption { get; private set; }

        /// <summary>
        /// 周推荐序号。
        /// </summary>
        /// <value>周推荐序号。</value>
        /* <example>105</example> */
        [JsonPropertyName("weekly_recommend_num")]
        public decimal? WeeklyRecommendNum { get { return this.WeeklyRecommendNumOption; } set { this.WeeklyRecommendNumOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner {\n");
            sb.Append("  Aid: ").Append(Aid).Append("\n");
            sb.Append("  Desc: ").Append(Desc).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  WeeklyRecommendNum: ").Append(WeeklyRecommendNum).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner" />
    /// </summary>
    public class GetSocialBilibiliVideoinfo200ResponseHonorReplyHonorInnerJsonConverter : JsonConverter<GetSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<decimal?> aid = default;
            Option<string?> desc = default;
            Option<decimal?> type = default;
            Option<decimal?> weeklyRecommendNum = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "aid":
                            aid = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "desc":
                            desc = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "type":
                            type = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "weekly_recommend_num":
                            weeklyRecommendNum = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (aid.IsSet && aid.Value == null)
                throw new ArgumentNullException(nameof(aid), "Property is not nullable for class GetSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner.");

            if (desc.IsSet && desc.Value == null)
                throw new ArgumentNullException(nameof(desc), "Property is not nullable for class GetSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner.");

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class GetSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner.");

            if (weeklyRecommendNum.IsSet && weeklyRecommendNum.Value == null)
                throw new ArgumentNullException(nameof(weeklyRecommendNum), "Property is not nullable for class GetSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner.");

            return new GetSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner(aid, desc, type, weeklyRecommendNum);
        }

        /// <summary>
        /// Serializes a <see cref="GetSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner getSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner getSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner.DescOption.IsSet && getSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner.Desc == null)
                throw new ArgumentNullException(nameof(getSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner.Desc), "Property is required for class GetSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner.");

            if (getSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner.AidOption.IsSet)
                writer.WriteNumber("aid", getSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner.AidOption.Value!.Value);

            if (getSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner.DescOption.IsSet)
                writer.WriteString("desc", getSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner.Desc);

            if (getSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner.TypeOption.IsSet)
                writer.WriteNumber("type", getSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner.TypeOption.Value!.Value);

            if (getSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner.WeeklyRecommendNumOption.IsSet)
                writer.WriteNumber("weekly_recommend_num", getSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner.WeeklyRecommendNumOption.Value!.Value);
        }
    }
}
