// <auto-generated>
/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using uapi-sdk-csharp.Client;

namespace uapi-sdk-csharp.Model
{
    /// <summary>
    /// 合集信息。若视频不属于合集则为 null。
    /// </summary>
    public partial class GetSocialBilibiliVideoinfo200ResponseUgcSeason : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetSocialBilibiliVideoinfo200ResponseUgcSeason" /> class.
        /// </summary>
        /// <param name="id">合集 ID。</param>
        /// <param name="title">合集标题。</param>
        /// <param name="cover">合集封面。</param>
        /// <param name="mid">合集作者 UID。</param>
        /// <param name="intro">合集简介。</param>
        /// <param name="epCount">合集内视频数量。</param>
        [JsonConstructor]
        public GetSocialBilibiliVideoinfo200ResponseUgcSeason(Option<decimal?> id = default, Option<string?> title = default, Option<string?> cover = default, Option<decimal?> mid = default, Option<string?> intro = default, Option<decimal?> epCount = default)
        {
            IdOption = id;
            TitleOption = title;
            CoverOption = cover;
            MidOption = mid;
            IntroOption = intro;
            EpCountOption = epCount;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> IdOption { get; private set; }

        /// <summary>
        /// 合集 ID。
        /// </summary>
        /// <value>合集 ID。</value>
        /* <example>12345</example> */
        [JsonPropertyName("id")]
        public decimal? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Title
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TitleOption { get; private set; }

        /// <summary>
        /// 合集标题。
        /// </summary>
        /// <value>合集标题。</value>
        /* <example>系列视频合集</example> */
        [JsonPropertyName("title")]
        public string? Title { get { return this.TitleOption; } set { this.TitleOption = new(value); } }

        /// <summary>
        /// Used to track the state of Cover
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CoverOption { get; private set; }

        /// <summary>
        /// 合集封面。
        /// </summary>
        /// <value>合集封面。</value>
        /* <example>http://i0.hdslb.com/bfs/archive/....jpg</example> */
        [JsonPropertyName("cover")]
        public string? Cover { get { return this.CoverOption; } set { this.CoverOption = new(value); } }

        /// <summary>
        /// Used to track the state of Mid
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> MidOption { get; private set; }

        /// <summary>
        /// 合集作者 UID。
        /// </summary>
        /// <value>合集作者 UID。</value>
        /* <example>483307278</example> */
        [JsonPropertyName("mid")]
        public decimal? Mid { get { return this.MidOption; } set { this.MidOption = new(value); } }

        /// <summary>
        /// Used to track the state of Intro
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IntroOption { get; private set; }

        /// <summary>
        /// 合集简介。
        /// </summary>
        /// <value>合集简介。</value>
        /* <example>这是一个合集</example> */
        [JsonPropertyName("intro")]
        public string? Intro { get { return this.IntroOption; } set { this.IntroOption = new(value); } }

        /// <summary>
        /// Used to track the state of EpCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> EpCountOption { get; private set; }

        /// <summary>
        /// 合集内视频数量。
        /// </summary>
        /// <value>合集内视频数量。</value>
        /* <example>12</example> */
        [JsonPropertyName("ep_count")]
        public decimal? EpCount { get { return this.EpCountOption; } set { this.EpCountOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetSocialBilibiliVideoinfo200ResponseUgcSeason {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Cover: ").Append(Cover).Append("\n");
            sb.Append("  Mid: ").Append(Mid).Append("\n");
            sb.Append("  Intro: ").Append(Intro).Append("\n");
            sb.Append("  EpCount: ").Append(EpCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetSocialBilibiliVideoinfo200ResponseUgcSeason" />
    /// </summary>
    public class GetSocialBilibiliVideoinfo200ResponseUgcSeasonJsonConverter : JsonConverter<GetSocialBilibiliVideoinfo200ResponseUgcSeason>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetSocialBilibiliVideoinfo200ResponseUgcSeason" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetSocialBilibiliVideoinfo200ResponseUgcSeason Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<decimal?> id = default;
            Option<string?> title = default;
            Option<string?> cover = default;
            Option<decimal?> mid = default;
            Option<string?> intro = default;
            Option<decimal?> epCount = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "title":
                            title = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "cover":
                            cover = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "mid":
                            mid = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "intro":
                            intro = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "ep_count":
                            epCount = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class GetSocialBilibiliVideoinfo200ResponseUgcSeason.");

            if (title.IsSet && title.Value == null)
                throw new ArgumentNullException(nameof(title), "Property is not nullable for class GetSocialBilibiliVideoinfo200ResponseUgcSeason.");

            if (cover.IsSet && cover.Value == null)
                throw new ArgumentNullException(nameof(cover), "Property is not nullable for class GetSocialBilibiliVideoinfo200ResponseUgcSeason.");

            if (mid.IsSet && mid.Value == null)
                throw new ArgumentNullException(nameof(mid), "Property is not nullable for class GetSocialBilibiliVideoinfo200ResponseUgcSeason.");

            if (intro.IsSet && intro.Value == null)
                throw new ArgumentNullException(nameof(intro), "Property is not nullable for class GetSocialBilibiliVideoinfo200ResponseUgcSeason.");

            if (epCount.IsSet && epCount.Value == null)
                throw new ArgumentNullException(nameof(epCount), "Property is not nullable for class GetSocialBilibiliVideoinfo200ResponseUgcSeason.");

            return new GetSocialBilibiliVideoinfo200ResponseUgcSeason(id, title, cover, mid, intro, epCount);
        }

        /// <summary>
        /// Serializes a <see cref="GetSocialBilibiliVideoinfo200ResponseUgcSeason" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getSocialBilibiliVideoinfo200ResponseUgcSeason"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetSocialBilibiliVideoinfo200ResponseUgcSeason getSocialBilibiliVideoinfo200ResponseUgcSeason, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getSocialBilibiliVideoinfo200ResponseUgcSeason, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetSocialBilibiliVideoinfo200ResponseUgcSeason" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getSocialBilibiliVideoinfo200ResponseUgcSeason"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetSocialBilibiliVideoinfo200ResponseUgcSeason getSocialBilibiliVideoinfo200ResponseUgcSeason, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getSocialBilibiliVideoinfo200ResponseUgcSeason.TitleOption.IsSet && getSocialBilibiliVideoinfo200ResponseUgcSeason.Title == null)
                throw new ArgumentNullException(nameof(getSocialBilibiliVideoinfo200ResponseUgcSeason.Title), "Property is required for class GetSocialBilibiliVideoinfo200ResponseUgcSeason.");

            if (getSocialBilibiliVideoinfo200ResponseUgcSeason.CoverOption.IsSet && getSocialBilibiliVideoinfo200ResponseUgcSeason.Cover == null)
                throw new ArgumentNullException(nameof(getSocialBilibiliVideoinfo200ResponseUgcSeason.Cover), "Property is required for class GetSocialBilibiliVideoinfo200ResponseUgcSeason.");

            if (getSocialBilibiliVideoinfo200ResponseUgcSeason.IntroOption.IsSet && getSocialBilibiliVideoinfo200ResponseUgcSeason.Intro == null)
                throw new ArgumentNullException(nameof(getSocialBilibiliVideoinfo200ResponseUgcSeason.Intro), "Property is required for class GetSocialBilibiliVideoinfo200ResponseUgcSeason.");

            if (getSocialBilibiliVideoinfo200ResponseUgcSeason.IdOption.IsSet)
                writer.WriteNumber("id", getSocialBilibiliVideoinfo200ResponseUgcSeason.IdOption.Value!.Value);

            if (getSocialBilibiliVideoinfo200ResponseUgcSeason.TitleOption.IsSet)
                writer.WriteString("title", getSocialBilibiliVideoinfo200ResponseUgcSeason.Title);

            if (getSocialBilibiliVideoinfo200ResponseUgcSeason.CoverOption.IsSet)
                writer.WriteString("cover", getSocialBilibiliVideoinfo200ResponseUgcSeason.Cover);

            if (getSocialBilibiliVideoinfo200ResponseUgcSeason.MidOption.IsSet)
                writer.WriteNumber("mid", getSocialBilibiliVideoinfo200ResponseUgcSeason.MidOption.Value!.Value);

            if (getSocialBilibiliVideoinfo200ResponseUgcSeason.IntroOption.IsSet)
                writer.WriteString("intro", getSocialBilibiliVideoinfo200ResponseUgcSeason.Intro);

            if (getSocialBilibiliVideoinfo200ResponseUgcSeason.EpCountOption.IsSet)
                writer.WriteNumber("ep_count", getSocialBilibiliVideoinfo200ResponseUgcSeason.EpCountOption.Value!.Value);
        }
    }
}
