// <auto-generated>
/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using uapi-sdk-csharp.Client;

namespace uapi-sdk-csharp.Model
{
    /// <summary>
    /// GetSocialBilibiliReplies200Response
    /// </summary>
    public partial class GetSocialBilibiliReplies200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetSocialBilibiliReplies200Response" /> class.
        /// </summary>
        /// <param name="page">page</param>
        /// <param name="hots">热门评论列表。结构与 &#x60;replies&#x60; 中的对象一致。如果当前页是第一页，且有热门评论，则此数组非空。</param>
        /// <param name="replies">当前页的评论列表。</param>
        [JsonConstructor]
        public GetSocialBilibiliReplies200Response(Option<GetSocialBilibiliReplies200ResponsePage?> page = default, Option<List<Object>?> hots = default, Option<List<GetSocialBilibiliReplies200ResponseRepliesInner>?> replies = default)
        {
            PageOption = page;
            HotsOption = hots;
            RepliesOption = replies;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Page
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<GetSocialBilibiliReplies200ResponsePage?> PageOption { get; private set; }

        /// <summary>
        /// Gets or Sets Page
        /// </summary>
        [JsonPropertyName("page")]
        public GetSocialBilibiliReplies200ResponsePage? Page { get { return this.PageOption; } set { this.PageOption = new(value); } }

        /// <summary>
        /// Used to track the state of Hots
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Object>?> HotsOption { get; private set; }

        /// <summary>
        /// 热门评论列表。结构与 &#x60;replies&#x60; 中的对象一致。如果当前页是第一页，且有热门评论，则此数组非空。
        /// </summary>
        /// <value>热门评论列表。结构与 &#x60;replies&#x60; 中的对象一致。如果当前页是第一页，且有热门评论，则此数组非空。</value>
        [JsonPropertyName("hots")]
        public List<Object>? Hots { get { return this.HotsOption; } set { this.HotsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Replies
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<GetSocialBilibiliReplies200ResponseRepliesInner>?> RepliesOption { get; private set; }

        /// <summary>
        /// 当前页的评论列表。
        /// </summary>
        /// <value>当前页的评论列表。</value>
        [JsonPropertyName("replies")]
        public List<GetSocialBilibiliReplies200ResponseRepliesInner>? Replies { get { return this.RepliesOption; } set { this.RepliesOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetSocialBilibiliReplies200Response {\n");
            sb.Append("  Page: ").Append(Page).Append("\n");
            sb.Append("  Hots: ").Append(Hots).Append("\n");
            sb.Append("  Replies: ").Append(Replies).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetSocialBilibiliReplies200Response" />
    /// </summary>
    public class GetSocialBilibiliReplies200ResponseJsonConverter : JsonConverter<GetSocialBilibiliReplies200Response>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetSocialBilibiliReplies200Response" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetSocialBilibiliReplies200Response Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<GetSocialBilibiliReplies200ResponsePage?> page = default;
            Option<List<Object>?> hots = default;
            Option<List<GetSocialBilibiliReplies200ResponseRepliesInner>?> replies = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "page":
                            page = new Option<GetSocialBilibiliReplies200ResponsePage?>(JsonSerializer.Deserialize<GetSocialBilibiliReplies200ResponsePage>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "hots":
                            hots = new Option<List<Object>?>(JsonSerializer.Deserialize<List<Object>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "replies":
                            replies = new Option<List<GetSocialBilibiliReplies200ResponseRepliesInner>?>(JsonSerializer.Deserialize<List<GetSocialBilibiliReplies200ResponseRepliesInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (page.IsSet && page.Value == null)
                throw new ArgumentNullException(nameof(page), "Property is not nullable for class GetSocialBilibiliReplies200Response.");

            if (replies.IsSet && replies.Value == null)
                throw new ArgumentNullException(nameof(replies), "Property is not nullable for class GetSocialBilibiliReplies200Response.");

            return new GetSocialBilibiliReplies200Response(page, hots, replies);
        }

        /// <summary>
        /// Serializes a <see cref="GetSocialBilibiliReplies200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getSocialBilibiliReplies200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetSocialBilibiliReplies200Response getSocialBilibiliReplies200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getSocialBilibiliReplies200Response, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetSocialBilibiliReplies200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getSocialBilibiliReplies200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetSocialBilibiliReplies200Response getSocialBilibiliReplies200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getSocialBilibiliReplies200Response.PageOption.IsSet && getSocialBilibiliReplies200Response.Page == null)
                throw new ArgumentNullException(nameof(getSocialBilibiliReplies200Response.Page), "Property is required for class GetSocialBilibiliReplies200Response.");

            if (getSocialBilibiliReplies200Response.RepliesOption.IsSet && getSocialBilibiliReplies200Response.Replies == null)
                throw new ArgumentNullException(nameof(getSocialBilibiliReplies200Response.Replies), "Property is required for class GetSocialBilibiliReplies200Response.");

            if (getSocialBilibiliReplies200Response.PageOption.IsSet)
            {
                writer.WritePropertyName("page");
                JsonSerializer.Serialize(writer, getSocialBilibiliReplies200Response.Page, jsonSerializerOptions);
            }
            if (getSocialBilibiliReplies200Response.HotsOption.IsSet)
                if (getSocialBilibiliReplies200Response.HotsOption.Value != null)
                {
                    writer.WritePropertyName("hots");
                    JsonSerializer.Serialize(writer, getSocialBilibiliReplies200Response.Hots, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("hots");
            if (getSocialBilibiliReplies200Response.RepliesOption.IsSet)
            {
                writer.WritePropertyName("replies");
                JsonSerializer.Serialize(writer, getSocialBilibiliReplies200Response.Replies, jsonSerializerOptions);
            }
        }
    }
}
