// <auto-generated>
/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using uapi-sdk-csharp.Client;

namespace uapi-sdk-csharp.Model
{
    /// <summary>
    /// 视频UP主信息。
    /// </summary>
    public partial class GetSocialBilibiliVideoinfo200ResponseOwner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetSocialBilibiliVideoinfo200ResponseOwner" /> class.
        /// </summary>
        /// <param name="mid">UP主的UID。</param>
        /// <param name="name">UP主昵称。</param>
        /// <param name="face">UP主头像的URL。</param>
        [JsonConstructor]
        public GetSocialBilibiliVideoinfo200ResponseOwner(Option<decimal?> mid = default, Option<string?> name = default, Option<string?> face = default)
        {
            MidOption = mid;
            NameOption = name;
            FaceOption = face;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Mid
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> MidOption { get; private set; }

        /// <summary>
        /// UP主的UID。
        /// </summary>
        /// <value>UP主的UID。</value>
        /* <example>2</example> */
        [JsonPropertyName("mid")]
        public decimal? Mid { get { return this.MidOption; } set { this.MidOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// UP主昵称。
        /// </summary>
        /// <value>UP主昵称。</value>
        /* <example>bishi</example> */
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Face
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FaceOption { get; private set; }

        /// <summary>
        /// UP主头像的URL。
        /// </summary>
        /// <value>UP主头像的URL。</value>
        /* <example>http://i2.hdslb.com/bfs/face/b0b721e6cb13e31af88cc45c432d6728c3065a6e.jpg</example> */
        [JsonPropertyName("face")]
        public string? Face { get { return this.FaceOption; } set { this.FaceOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetSocialBilibiliVideoinfo200ResponseOwner {\n");
            sb.Append("  Mid: ").Append(Mid).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Face: ").Append(Face).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetSocialBilibiliVideoinfo200ResponseOwner" />
    /// </summary>
    public class GetSocialBilibiliVideoinfo200ResponseOwnerJsonConverter : JsonConverter<GetSocialBilibiliVideoinfo200ResponseOwner>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetSocialBilibiliVideoinfo200ResponseOwner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetSocialBilibiliVideoinfo200ResponseOwner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<decimal?> mid = default;
            Option<string?> name = default;
            Option<string?> face = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "mid":
                            mid = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "face":
                            face = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (mid.IsSet && mid.Value == null)
                throw new ArgumentNullException(nameof(mid), "Property is not nullable for class GetSocialBilibiliVideoinfo200ResponseOwner.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class GetSocialBilibiliVideoinfo200ResponseOwner.");

            if (face.IsSet && face.Value == null)
                throw new ArgumentNullException(nameof(face), "Property is not nullable for class GetSocialBilibiliVideoinfo200ResponseOwner.");

            return new GetSocialBilibiliVideoinfo200ResponseOwner(mid, name, face);
        }

        /// <summary>
        /// Serializes a <see cref="GetSocialBilibiliVideoinfo200ResponseOwner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getSocialBilibiliVideoinfo200ResponseOwner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetSocialBilibiliVideoinfo200ResponseOwner getSocialBilibiliVideoinfo200ResponseOwner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getSocialBilibiliVideoinfo200ResponseOwner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetSocialBilibiliVideoinfo200ResponseOwner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getSocialBilibiliVideoinfo200ResponseOwner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetSocialBilibiliVideoinfo200ResponseOwner getSocialBilibiliVideoinfo200ResponseOwner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getSocialBilibiliVideoinfo200ResponseOwner.NameOption.IsSet && getSocialBilibiliVideoinfo200ResponseOwner.Name == null)
                throw new ArgumentNullException(nameof(getSocialBilibiliVideoinfo200ResponseOwner.Name), "Property is required for class GetSocialBilibiliVideoinfo200ResponseOwner.");

            if (getSocialBilibiliVideoinfo200ResponseOwner.FaceOption.IsSet && getSocialBilibiliVideoinfo200ResponseOwner.Face == null)
                throw new ArgumentNullException(nameof(getSocialBilibiliVideoinfo200ResponseOwner.Face), "Property is required for class GetSocialBilibiliVideoinfo200ResponseOwner.");

            if (getSocialBilibiliVideoinfo200ResponseOwner.MidOption.IsSet)
                writer.WriteNumber("mid", getSocialBilibiliVideoinfo200ResponseOwner.MidOption.Value!.Value);

            if (getSocialBilibiliVideoinfo200ResponseOwner.NameOption.IsSet)
                writer.WriteString("name", getSocialBilibiliVideoinfo200ResponseOwner.Name);

            if (getSocialBilibiliVideoinfo200ResponseOwner.FaceOption.IsSet)
                writer.WriteString("face", getSocialBilibiliVideoinfo200ResponseOwner.Face);
        }
    }
}
