// <auto-generated>
/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using uapi-sdk-csharp.Client;

namespace uapi-sdk-csharp.Model
{
    /// <summary>
    /// PostClipzyStoreRequest
    /// </summary>
    public partial class PostClipzyStoreRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostClipzyStoreRequest" /> class.
        /// </summary>
        /// <param name="compressedData">必需：经过加密和 LZString 压缩后的 Base64 字符串。请参考文档首页的JS代码示例。</param>
        /// <param name="ttl">可选：片段的留存时间（秒）。正数表示秒数（最大约30天），-1 表示永久存储。默认为 3600。</param>
        [JsonConstructor]
        public PostClipzyStoreRequest(string compressedData, Option<decimal?> ttl = default)
        {
            CompressedData = compressedData;
            TtlOption = ttl;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// 必需：经过加密和 LZString 压缩后的 Base64 字符串。请参考文档首页的JS代码示例。
        /// </summary>
        /// <value>必需：经过加密和 LZString 压缩后的 Base64 字符串。请参考文档首页的JS代码示例。</value>
        /* <example>PIZQqgLgUgNg6gEQEYAUCuBrA7gSQBoDMAiigPakCOAYgQIYBKEA7AFbABqAEiAJYBmAYSJUAznHbsAcgBMBAFQDSAegCcALz4BZKHDwql9DADtOCqvQCCATQowAWhgVgYAUwBMAFgC8QA&#x3D;&#x3D;</example> */
        [JsonPropertyName("compressedData")]
        public string CompressedData { get; set; }

        /// <summary>
        /// Used to track the state of Ttl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> TtlOption { get; private set; }

        /// <summary>
        /// 可选：片段的留存时间（秒）。正数表示秒数（最大约30天），-1 表示永久存储。默认为 3600。
        /// </summary>
        /// <value>可选：片段的留存时间（秒）。正数表示秒数（最大约30天），-1 表示永久存储。默认为 3600。</value>
        /* <example>3600</example> */
        [JsonPropertyName("ttl")]
        public decimal? Ttl { get { return this.TtlOption; } set { this.TtlOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PostClipzyStoreRequest {\n");
            sb.Append("  CompressedData: ").Append(CompressedData).Append("\n");
            sb.Append("  Ttl: ").Append(Ttl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PostClipzyStoreRequest" />
    /// </summary>
    public class PostClipzyStoreRequestJsonConverter : JsonConverter<PostClipzyStoreRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="PostClipzyStoreRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PostClipzyStoreRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> compressedData = default;
            Option<decimal?> ttl = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "compressedData":
                            compressedData = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "ttl":
                            ttl = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!compressedData.IsSet)
                throw new ArgumentException("Property is required for class PostClipzyStoreRequest.", nameof(compressedData));

            if (compressedData.IsSet && compressedData.Value == null)
                throw new ArgumentNullException(nameof(compressedData), "Property is not nullable for class PostClipzyStoreRequest.");

            if (ttl.IsSet && ttl.Value == null)
                throw new ArgumentNullException(nameof(ttl), "Property is not nullable for class PostClipzyStoreRequest.");

            return new PostClipzyStoreRequest(compressedData.Value!, ttl);
        }

        /// <summary>
        /// Serializes a <see cref="PostClipzyStoreRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="postClipzyStoreRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PostClipzyStoreRequest postClipzyStoreRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, postClipzyStoreRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PostClipzyStoreRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="postClipzyStoreRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PostClipzyStoreRequest postClipzyStoreRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (postClipzyStoreRequest.CompressedData == null)
                throw new ArgumentNullException(nameof(postClipzyStoreRequest.CompressedData), "Property is required for class PostClipzyStoreRequest.");

            writer.WriteString("compressedData", postClipzyStoreRequest.CompressedData);

            if (postClipzyStoreRequest.TtlOption.IsSet)
                writer.WriteNumber("ttl", postClipzyStoreRequest.TtlOption.Value!.Value);
        }
    }
}
