// <auto-generated>
/*
 * UAPI
 *
 * UAPI 官方接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using uapi-sdk-csharp.Client;

namespace uapi-sdk-csharp.Model
{
    /// <summary>
    /// PostSearchAggregate200Response
    /// </summary>
    public partial class PostSearchAggregate200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostSearchAggregate200Response" /> class.
        /// </summary>
        /// <param name="query">实际执行的搜索查询</param>
        /// <param name="totalResults">搜索结果总数</param>
        /// <param name="results">搜索结果列表</param>
        /// <param name="sources">各搜索引擎的结果数量统计</param>
        /// <param name="processTimeMs">处理耗时（毫秒）</param>
        /// <param name="cached">结果是否来自缓存</param>
        [JsonConstructor]
        public PostSearchAggregate200Response(Option<string?> query = default, Option<int?> totalResults = default, Option<List<PostSearchAggregate200ResponseResultsInner>?> results = default, Option<List<PostSearchAggregate200ResponseSourcesInner>?> sources = default, Option<int?> processTimeMs = default, Option<bool?> cached = default)
        {
            QueryOption = query;
            TotalResultsOption = totalResults;
            ResultsOption = results;
            SourcesOption = sources;
            ProcessTimeMsOption = processTimeMs;
            CachedOption = cached;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Query
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> QueryOption { get; private set; }

        /// <summary>
        /// 实际执行的搜索查询
        /// </summary>
        /// <value>实际执行的搜索查询</value>
        /* <example>Go最新的版本是多少</example> */
        [JsonPropertyName("query")]
        public string? Query { get { return this.QueryOption; } set { this.QueryOption = new(value); } }

        /// <summary>
        /// Used to track the state of TotalResults
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> TotalResultsOption { get; private set; }

        /// <summary>
        /// 搜索结果总数
        /// </summary>
        /// <value>搜索结果总数</value>
        [JsonPropertyName("total_results")]
        public int? TotalResults { get { return this.TotalResultsOption; } set { this.TotalResultsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Results
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<PostSearchAggregate200ResponseResultsInner>?> ResultsOption { get; private set; }

        /// <summary>
        /// 搜索结果列表
        /// </summary>
        /// <value>搜索结果列表</value>
        [JsonPropertyName("results")]
        public List<PostSearchAggregate200ResponseResultsInner>? Results { get { return this.ResultsOption; } set { this.ResultsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Sources
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<PostSearchAggregate200ResponseSourcesInner>?> SourcesOption { get; private set; }

        /// <summary>
        /// 各搜索引擎的结果数量统计
        /// </summary>
        /// <value>各搜索引擎的结果数量统计</value>
        [JsonPropertyName("sources")]
        public List<PostSearchAggregate200ResponseSourcesInner>? Sources { get { return this.SourcesOption; } set { this.SourcesOption = new(value); } }

        /// <summary>
        /// Used to track the state of ProcessTimeMs
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ProcessTimeMsOption { get; private set; }

        /// <summary>
        /// 处理耗时（毫秒）
        /// </summary>
        /// <value>处理耗时（毫秒）</value>
        [JsonPropertyName("process_time_ms")]
        public int? ProcessTimeMs { get { return this.ProcessTimeMsOption; } set { this.ProcessTimeMsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Cached
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> CachedOption { get; private set; }

        /// <summary>
        /// 结果是否来自缓存
        /// </summary>
        /// <value>结果是否来自缓存</value>
        [JsonPropertyName("cached")]
        public bool? Cached { get { return this.CachedOption; } set { this.CachedOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PostSearchAggregate200Response {\n");
            sb.Append("  Query: ").Append(Query).Append("\n");
            sb.Append("  TotalResults: ").Append(TotalResults).Append("\n");
            sb.Append("  Results: ").Append(Results).Append("\n");
            sb.Append("  Sources: ").Append(Sources).Append("\n");
            sb.Append("  ProcessTimeMs: ").Append(ProcessTimeMs).Append("\n");
            sb.Append("  Cached: ").Append(Cached).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PostSearchAggregate200Response" />
    /// </summary>
    public class PostSearchAggregate200ResponseJsonConverter : JsonConverter<PostSearchAggregate200Response>
    {
        /// <summary>
        /// Deserializes json to <see cref="PostSearchAggregate200Response" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PostSearchAggregate200Response Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> query = default;
            Option<int?> totalResults = default;
            Option<List<PostSearchAggregate200ResponseResultsInner>?> results = default;
            Option<List<PostSearchAggregate200ResponseSourcesInner>?> sources = default;
            Option<int?> processTimeMs = default;
            Option<bool?> cached = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "query":
                            query = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "total_results":
                            totalResults = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "results":
                            results = new Option<List<PostSearchAggregate200ResponseResultsInner>?>(JsonSerializer.Deserialize<List<PostSearchAggregate200ResponseResultsInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "sources":
                            sources = new Option<List<PostSearchAggregate200ResponseSourcesInner>?>(JsonSerializer.Deserialize<List<PostSearchAggregate200ResponseSourcesInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "process_time_ms":
                            processTimeMs = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "cached":
                            cached = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (query.IsSet && query.Value == null)
                throw new ArgumentNullException(nameof(query), "Property is not nullable for class PostSearchAggregate200Response.");

            if (totalResults.IsSet && totalResults.Value == null)
                throw new ArgumentNullException(nameof(totalResults), "Property is not nullable for class PostSearchAggregate200Response.");

            if (results.IsSet && results.Value == null)
                throw new ArgumentNullException(nameof(results), "Property is not nullable for class PostSearchAggregate200Response.");

            if (sources.IsSet && sources.Value == null)
                throw new ArgumentNullException(nameof(sources), "Property is not nullable for class PostSearchAggregate200Response.");

            if (processTimeMs.IsSet && processTimeMs.Value == null)
                throw new ArgumentNullException(nameof(processTimeMs), "Property is not nullable for class PostSearchAggregate200Response.");

            if (cached.IsSet && cached.Value == null)
                throw new ArgumentNullException(nameof(cached), "Property is not nullable for class PostSearchAggregate200Response.");

            return new PostSearchAggregate200Response(query, totalResults, results, sources, processTimeMs, cached);
        }

        /// <summary>
        /// Serializes a <see cref="PostSearchAggregate200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="postSearchAggregate200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PostSearchAggregate200Response postSearchAggregate200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, postSearchAggregate200Response, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PostSearchAggregate200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="postSearchAggregate200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PostSearchAggregate200Response postSearchAggregate200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            if (postSearchAggregate200Response.QueryOption.IsSet && postSearchAggregate200Response.Query == null)
                throw new ArgumentNullException(nameof(postSearchAggregate200Response.Query), "Property is required for class PostSearchAggregate200Response.");

            if (postSearchAggregate200Response.ResultsOption.IsSet && postSearchAggregate200Response.Results == null)
                throw new ArgumentNullException(nameof(postSearchAggregate200Response.Results), "Property is required for class PostSearchAggregate200Response.");

            if (postSearchAggregate200Response.SourcesOption.IsSet && postSearchAggregate200Response.Sources == null)
                throw new ArgumentNullException(nameof(postSearchAggregate200Response.Sources), "Property is required for class PostSearchAggregate200Response.");

            if (postSearchAggregate200Response.QueryOption.IsSet)
                writer.WriteString("query", postSearchAggregate200Response.Query);

            if (postSearchAggregate200Response.TotalResultsOption.IsSet)
                writer.WriteNumber("total_results", postSearchAggregate200Response.TotalResultsOption.Value!.Value);

            if (postSearchAggregate200Response.ResultsOption.IsSet)
            {
                writer.WritePropertyName("results");
                JsonSerializer.Serialize(writer, postSearchAggregate200Response.Results, jsonSerializerOptions);
            }
            if (postSearchAggregate200Response.SourcesOption.IsSet)
            {
                writer.WritePropertyName("sources");
                JsonSerializer.Serialize(writer, postSearchAggregate200Response.Sources, jsonSerializerOptions);
            }
            if (postSearchAggregate200Response.ProcessTimeMsOption.IsSet)
                writer.WriteNumber("process_time_ms", postSearchAggregate200Response.ProcessTimeMsOption.Value!.Value);

            if (postSearchAggregate200Response.CachedOption.IsSet)
                writer.WriteBoolean("cached", postSearchAggregate200Response.CachedOption.Value!.Value);
        }
    }
}
