// <auto-generated>
/*
 * UAPI OpenAPI
 *
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using uapi-sdk-csharp.Client;

namespace uapi-sdk-csharp.Model
{
    /// <summary>
    /// PostImageOcr400Response
    /// </summary>
    public partial class PostImageOcr400Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostImageOcr400Response" /> class.
        /// </summary>
        /// <param name="postImageOcr400ResponseOneOf"></param>
        public PostImageOcr400Response(PostImageOcr400ResponseOneOf postImageOcr400ResponseOneOf)
        {
            PostImageOcr400ResponseOneOf = postImageOcr400ResponseOneOf;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PostImageOcr400Response" /> class.
        /// </summary>
        /// <param name="postImageOcr400ResponseOneOf1"></param>
        public PostImageOcr400Response(PostImageOcr400ResponseOneOf1 postImageOcr400ResponseOneOf1)
        {
            PostImageOcr400ResponseOneOf1 = postImageOcr400ResponseOneOf1;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PostImageOcr400Response" /> class.
        /// </summary>
        /// <param name="base64"></param>
        public PostImageOcr400Response(Base64 base64)
        {
            Base64 = base64;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets PostImageOcr400ResponseOneOf
        /// </summary>
        public PostImageOcr400ResponseOneOf? PostImageOcr400ResponseOneOf { get; set; }

        /// <summary>
        /// Gets or Sets PostImageOcr400ResponseOneOf1
        /// </summary>
        public PostImageOcr400ResponseOneOf1? PostImageOcr400ResponseOneOf1 { get; set; }

        /// <summary>
        /// Gets or Sets Base64
        /// </summary>
        public Base64? Base64 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PostImageOcr400Response {\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PostImageOcr400Response" />
    /// </summary>
    public class PostImageOcr400ResponseJsonConverter : JsonConverter<PostImageOcr400Response>
    {
        /// <summary>
        /// Deserializes json to <see cref="PostImageOcr400Response" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PostImageOcr400Response Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            PostImageOcr400ResponseOneOf? postImageOcr400ResponseOneOf = default;
            PostImageOcr400ResponseOneOf1? postImageOcr400ResponseOneOf1 = default;
            Base64? base64 = default;

            Utf8JsonReader utf8JsonReaderOneOf = utf8JsonReader;
            while (utf8JsonReaderOneOf.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReaderOneOf.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReaderOneOf.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReaderOneOf.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReaderOneOf.CurrentDepth)
                    break;

                if (utf8JsonReaderOneOf.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReaderOneOf.CurrentDepth - 1)
                {
                    Utf8JsonReader utf8JsonReaderPostImageOcr400ResponseOneOf = utf8JsonReader;
                    ClientUtils.TryDeserialize<PostImageOcr400ResponseOneOf?>(ref utf8JsonReaderPostImageOcr400ResponseOneOf, jsonSerializerOptions, out postImageOcr400ResponseOneOf);

                    Utf8JsonReader utf8JsonReaderPostImageOcr400ResponseOneOf1 = utf8JsonReader;
                    ClientUtils.TryDeserialize<PostImageOcr400ResponseOneOf1?>(ref utf8JsonReaderPostImageOcr400ResponseOneOf1, jsonSerializerOptions, out postImageOcr400ResponseOneOf1);

                    Utf8JsonReader utf8JsonReaderBase64 = utf8JsonReader;
                    ClientUtils.TryDeserialize<Base64?>(ref utf8JsonReaderBase64, jsonSerializerOptions, out base64);
                }
            }

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        default:
                            break;
                    }
                }
            }

            if (postImageOcr400ResponseOneOf != null)
                return new PostImageOcr400Response(postImageOcr400ResponseOneOf);

            if (postImageOcr400ResponseOneOf1 != null)
                return new PostImageOcr400Response(postImageOcr400ResponseOneOf1);

            if (base64 != null)
                return new PostImageOcr400Response(base64);

            throw new JsonException();
        }

        /// <summary>
        /// Serializes a <see cref="PostImageOcr400Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="postImageOcr400Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PostImageOcr400Response postImageOcr400Response, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, postImageOcr400Response, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PostImageOcr400Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="postImageOcr400Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PostImageOcr400Response postImageOcr400Response, JsonSerializerOptions jsonSerializerOptions)
        {

        }
    }
}
