// <auto-generated>
/*
 * UAPI OpenAPI
 *
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using uapi-sdk-csharp.Client;

namespace uapi-sdk-csharp.Model
{
    /// <summary>
    /// PostWatermarkProducerCodeRequest
    /// </summary>
    public partial class PostWatermarkProducerCodeRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostWatermarkProducerCodeRequest" /> class.
        /// </summary>
        /// <param name="binding">主体绑定的证件类型。组织需使用统一社会信用代码；个人可选身份证、手机号、护照或网号。</param>
        /// <param name="code">待校验的 27 位现成编码。填写后接口将直接执行合法性校验。</param>
        /// <param name="identifier">证件号实际内容。长度需匹配选择的类型（如统一社会信用代码 18 位、手机号 11 位）。</param>
        /// <param name="modelCode">4 位自定义模型或应用码（可选）。未提供时扩展段将默认填充 00000。</param>
        /// <param name="serviceType">服务角色类型（仅在提供模型应用码时一同生效）。</param>
        /// <param name="subjectType">主体类型是组织还是个人。</param>
        [JsonConstructor]
        public PostWatermarkProducerCodeRequest(Option<BindingEnum?> binding = default, Option<string?> code = default, Option<string?> identifier = default, Option<string?> modelCode = default, Option<ServiceTypeEnum?> serviceType = default, Option<SubjectTypeEnum?> subjectType = default)
        {
            BindingOption = binding;
            CodeOption = code;
            IdentifierOption = identifier;
            ModelCodeOption = modelCode;
            ServiceTypeOption = serviceType;
            SubjectTypeOption = subjectType;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// 主体绑定的证件类型。组织需使用统一社会信用代码；个人可选身份证、手机号、护照或网号。
        /// </summary>
        /// <value>主体绑定的证件类型。组织需使用统一社会信用代码；个人可选身份证、手机号、护照或网号。</value>
        public enum BindingEnum
        {
            /// <summary>
            /// Enum Uscc for value: uscc
            /// </summary>
            Uscc = 1,

            /// <summary>
            /// Enum Id for value: id
            /// </summary>
            Id = 2,

            /// <summary>
            /// Enum Phone for value: phone
            /// </summary>
            Phone = 3,

            /// <summary>
            /// Enum Passport for value: passport
            /// </summary>
            Passport = 4,

            /// <summary>
            /// Enum Netid for value: netid
            /// </summary>
            Netid = 5
        }

        /// <summary>
        /// Returns a <see cref="BindingEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static BindingEnum BindingEnumFromString(string value)
        {
            if (value.Equals("uscc"))
                return BindingEnum.Uscc;

            if (value.Equals("id"))
                return BindingEnum.Id;

            if (value.Equals("phone"))
                return BindingEnum.Phone;

            if (value.Equals("passport"))
                return BindingEnum.Passport;

            if (value.Equals("netid"))
                return BindingEnum.Netid;

            throw new NotImplementedException($"Could not convert value to type BindingEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="BindingEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static BindingEnum? BindingEnumFromStringOrDefault(string value)
        {
            if (value.Equals("uscc"))
                return BindingEnum.Uscc;

            if (value.Equals("id"))
                return BindingEnum.Id;

            if (value.Equals("phone"))
                return BindingEnum.Phone;

            if (value.Equals("passport"))
                return BindingEnum.Passport;

            if (value.Equals("netid"))
                return BindingEnum.Netid;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="BindingEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string BindingEnumToJsonValue(BindingEnum? value)
        {
            if (value == BindingEnum.Uscc)
                return "uscc";

            if (value == BindingEnum.Id)
                return "id";

            if (value == BindingEnum.Phone)
                return "phone";

            if (value == BindingEnum.Passport)
                return "passport";

            if (value == BindingEnum.Netid)
                return "netid";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Binding
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<BindingEnum?> BindingOption { get; private set; }

        /// <summary>
        /// 主体绑定的证件类型。组织需使用统一社会信用代码；个人可选身份证、手机号、护照或网号。
        /// </summary>
        /// <value>主体绑定的证件类型。组织需使用统一社会信用代码；个人可选身份证、手机号、护照或网号。</value>
        /* <example>phone</example> */
        [JsonPropertyName("binding")]
        public BindingEnum? Binding { get { return this.BindingOption; } set { this.BindingOption = new(value); } }

        /// <summary>
        /// 服务角色类型（仅在提供模型应用码时一同生效）。
        /// </summary>
        /// <value>服务角色类型（仅在提供模型应用码时一同生效）。</value>
        public enum ServiceTypeEnum
        {
            /// <summary>
            /// Enum Generation for value: generation
            /// </summary>
            Generation = 1,

            /// <summary>
            /// Enum Propagation for value: propagation
            /// </summary>
            Propagation = 2
        }

        /// <summary>
        /// Returns a <see cref="ServiceTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static ServiceTypeEnum ServiceTypeEnumFromString(string value)
        {
            if (value.Equals("generation"))
                return ServiceTypeEnum.Generation;

            if (value.Equals("propagation"))
                return ServiceTypeEnum.Propagation;

            throw new NotImplementedException($"Could not convert value to type ServiceTypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="ServiceTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ServiceTypeEnum? ServiceTypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("generation"))
                return ServiceTypeEnum.Generation;

            if (value.Equals("propagation"))
                return ServiceTypeEnum.Propagation;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ServiceTypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ServiceTypeEnumToJsonValue(ServiceTypeEnum? value)
        {
            if (value == ServiceTypeEnum.Generation)
                return "generation";

            if (value == ServiceTypeEnum.Propagation)
                return "propagation";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of ServiceType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ServiceTypeEnum?> ServiceTypeOption { get; private set; }

        /// <summary>
        /// 服务角色类型（仅在提供模型应用码时一同生效）。
        /// </summary>
        /// <value>服务角色类型（仅在提供模型应用码时一同生效）。</value>
        /* <example>generation</example> */
        [JsonPropertyName("service_type")]
        public ServiceTypeEnum? ServiceType { get { return this.ServiceTypeOption; } set { this.ServiceTypeOption = new(value); } }

        /// <summary>
        /// 主体类型是组织还是个人。
        /// </summary>
        /// <value>主体类型是组织还是个人。</value>
        public enum SubjectTypeEnum
        {
            /// <summary>
            /// Enum Org for value: org
            /// </summary>
            Org = 1,

            /// <summary>
            /// Enum Person for value: person
            /// </summary>
            Person = 2
        }

        /// <summary>
        /// Returns a <see cref="SubjectTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static SubjectTypeEnum SubjectTypeEnumFromString(string value)
        {
            if (value.Equals("org"))
                return SubjectTypeEnum.Org;

            if (value.Equals("person"))
                return SubjectTypeEnum.Person;

            throw new NotImplementedException($"Could not convert value to type SubjectTypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="SubjectTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static SubjectTypeEnum? SubjectTypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("org"))
                return SubjectTypeEnum.Org;

            if (value.Equals("person"))
                return SubjectTypeEnum.Person;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="SubjectTypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string SubjectTypeEnumToJsonValue(SubjectTypeEnum? value)
        {
            if (value == SubjectTypeEnum.Org)
                return "org";

            if (value == SubjectTypeEnum.Person)
                return "person";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of SubjectType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<SubjectTypeEnum?> SubjectTypeOption { get; private set; }

        /// <summary>
        /// 主体类型是组织还是个人。
        /// </summary>
        /// <value>主体类型是组织还是个人。</value>
        /* <example>person</example> */
        [JsonPropertyName("subject_type")]
        public SubjectTypeEnum? SubjectType { get { return this.SubjectTypeOption; } set { this.SubjectTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Code
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CodeOption { get; private set; }

        /// <summary>
        /// 待校验的 27 位现成编码。填写后接口将直接执行合法性校验。
        /// </summary>
        /// <value>待校验的 27 位现成编码。填写后接口将直接执行合法性校验。</value>
        [JsonPropertyName("code")]
        public string? Code { get { return this.CodeOption; } set { this.CodeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Identifier
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IdentifierOption { get; private set; }

        /// <summary>
        /// 证件号实际内容。长度需匹配选择的类型（如统一社会信用代码 18 位、手机号 11 位）。
        /// </summary>
        /// <value>证件号实际内容。长度需匹配选择的类型（如统一社会信用代码 18 位、手机号 11 位）。</value>
        /* <example>13800138000</example> */
        [JsonPropertyName("identifier")]
        public string? Identifier { get { return this.IdentifierOption; } set { this.IdentifierOption = new(value); } }

        /// <summary>
        /// Used to track the state of ModelCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ModelCodeOption { get; private set; }

        /// <summary>
        /// 4 位自定义模型或应用码（可选）。未提供时扩展段将默认填充 00000。
        /// </summary>
        /// <value>4 位自定义模型或应用码（可选）。未提供时扩展段将默认填充 00000。</value>
        /* <example>0001</example> */
        [JsonPropertyName("model_code")]
        public string? ModelCode { get { return this.ModelCodeOption; } set { this.ModelCodeOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PostWatermarkProducerCodeRequest {\n");
            sb.Append("  Binding: ").Append(Binding).Append("\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Identifier: ").Append(Identifier).Append("\n");
            sb.Append("  ModelCode: ").Append(ModelCode).Append("\n");
            sb.Append("  ServiceType: ").Append(ServiceType).Append("\n");
            sb.Append("  SubjectType: ").Append(SubjectType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PostWatermarkProducerCodeRequest" />
    /// </summary>
    public class PostWatermarkProducerCodeRequestJsonConverter : JsonConverter<PostWatermarkProducerCodeRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="PostWatermarkProducerCodeRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PostWatermarkProducerCodeRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<PostWatermarkProducerCodeRequest.BindingEnum?> binding = default;
            Option<string?> code = default;
            Option<string?> identifier = default;
            Option<string?> modelCode = default;
            Option<PostWatermarkProducerCodeRequest.ServiceTypeEnum?> serviceType = default;
            Option<PostWatermarkProducerCodeRequest.SubjectTypeEnum?> subjectType = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "binding":
                            string? bindingRawValue = utf8JsonReader.GetString();
                            if (bindingRawValue != null)
                                binding = new Option<PostWatermarkProducerCodeRequest.BindingEnum?>(PostWatermarkProducerCodeRequest.BindingEnumFromStringOrDefault(bindingRawValue));
                            break;
                        case "code":
                            code = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "identifier":
                            identifier = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "model_code":
                            modelCode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "service_type":
                            string? serviceTypeRawValue = utf8JsonReader.GetString();
                            if (serviceTypeRawValue != null)
                                serviceType = new Option<PostWatermarkProducerCodeRequest.ServiceTypeEnum?>(PostWatermarkProducerCodeRequest.ServiceTypeEnumFromStringOrDefault(serviceTypeRawValue));
                            break;
                        case "subject_type":
                            string? subjectTypeRawValue = utf8JsonReader.GetString();
                            if (subjectTypeRawValue != null)
                                subjectType = new Option<PostWatermarkProducerCodeRequest.SubjectTypeEnum?>(PostWatermarkProducerCodeRequest.SubjectTypeEnumFromStringOrDefault(subjectTypeRawValue));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (binding.IsSet && binding.Value == null)
                throw new ArgumentNullException(nameof(binding), "Property is not nullable for class PostWatermarkProducerCodeRequest.");

            if (code.IsSet && code.Value == null)
                throw new ArgumentNullException(nameof(code), "Property is not nullable for class PostWatermarkProducerCodeRequest.");

            if (identifier.IsSet && identifier.Value == null)
                throw new ArgumentNullException(nameof(identifier), "Property is not nullable for class PostWatermarkProducerCodeRequest.");

            if (modelCode.IsSet && modelCode.Value == null)
                throw new ArgumentNullException(nameof(modelCode), "Property is not nullable for class PostWatermarkProducerCodeRequest.");

            if (serviceType.IsSet && serviceType.Value == null)
                throw new ArgumentNullException(nameof(serviceType), "Property is not nullable for class PostWatermarkProducerCodeRequest.");

            if (subjectType.IsSet && subjectType.Value == null)
                throw new ArgumentNullException(nameof(subjectType), "Property is not nullable for class PostWatermarkProducerCodeRequest.");

            return new PostWatermarkProducerCodeRequest(binding, code, identifier, modelCode, serviceType, subjectType);
        }

        /// <summary>
        /// Serializes a <see cref="PostWatermarkProducerCodeRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="postWatermarkProducerCodeRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PostWatermarkProducerCodeRequest postWatermarkProducerCodeRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, postWatermarkProducerCodeRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PostWatermarkProducerCodeRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="postWatermarkProducerCodeRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PostWatermarkProducerCodeRequest postWatermarkProducerCodeRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (postWatermarkProducerCodeRequest.CodeOption.IsSet && postWatermarkProducerCodeRequest.Code == null)
                throw new ArgumentNullException(nameof(postWatermarkProducerCodeRequest.Code), "Property is required for class PostWatermarkProducerCodeRequest.");

            if (postWatermarkProducerCodeRequest.IdentifierOption.IsSet && postWatermarkProducerCodeRequest.Identifier == null)
                throw new ArgumentNullException(nameof(postWatermarkProducerCodeRequest.Identifier), "Property is required for class PostWatermarkProducerCodeRequest.");

            if (postWatermarkProducerCodeRequest.ModelCodeOption.IsSet && postWatermarkProducerCodeRequest.ModelCode == null)
                throw new ArgumentNullException(nameof(postWatermarkProducerCodeRequest.ModelCode), "Property is required for class PostWatermarkProducerCodeRequest.");

            var bindingRawValue = PostWatermarkProducerCodeRequest.BindingEnumToJsonValue(postWatermarkProducerCodeRequest.BindingOption.Value!.Value);
            writer.WriteString("binding", bindingRawValue);
            if (postWatermarkProducerCodeRequest.CodeOption.IsSet)
                writer.WriteString("code", postWatermarkProducerCodeRequest.Code);

            if (postWatermarkProducerCodeRequest.IdentifierOption.IsSet)
                writer.WriteString("identifier", postWatermarkProducerCodeRequest.Identifier);

            if (postWatermarkProducerCodeRequest.ModelCodeOption.IsSet)
                writer.WriteString("model_code", postWatermarkProducerCodeRequest.ModelCode);

            var serviceTypeRawValue = PostWatermarkProducerCodeRequest.ServiceTypeEnumToJsonValue(postWatermarkProducerCodeRequest.ServiceTypeOption.Value!.Value);
            writer.WriteString("service_type", serviceTypeRawValue);
            var subjectTypeRawValue = PostWatermarkProducerCodeRequest.SubjectTypeEnumToJsonValue(postWatermarkProducerCodeRequest.SubjectTypeOption.Value!.Value);
            writer.WriteString("subject_type", subjectTypeRawValue);
        }
    }
}
