// <auto-generated>
/*
 * UAPI OpenAPI
 *
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using uapi-sdk-csharp.Client;

namespace uapi-sdk-csharp.Model
{
    /// <summary>
    /// 作者扩展信息，部分语料返回。
    /// </summary>
    public partial class RandomAuthorinfo : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RandomAuthorinfo" /> class.
        /// </summary>
        /// <param name="bio">bio</param>
        /// <param name="description">description</param>
        /// <param name="id">id</param>
        /// <param name="link">link</param>
        /// <param name="name">name</param>
        [JsonConstructor]
        public RandomAuthorinfo(Option<string?> bio = default, Option<string?> description = default, Option<string?> id = default, Option<string?> link = default, Option<string?> name = default)
        {
            BioOption = bio;
            DescriptionOption = description;
            IdOption = id;
            LinkOption = link;
            NameOption = name;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Bio
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> BioOption { get; private set; }

        /// <summary>
        /// Gets or Sets Bio
        /// </summary>
        /* <example>代表作包括《夏目友人帐》。</example> */
        [JsonPropertyName("bio")]
        public string? Bio { get { return this.BioOption; } set { this.BioOption = new(value); } }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        /* <example>漫画作者</example> */
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        /* <example>natsume</example> */
        [JsonPropertyName("id")]
        public string? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Link
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LinkOption { get; private set; }

        /// <summary>
        /// Gets or Sets Link
        /// </summary>
        /* <example>https://example.com/author/natsume</example> */
        [JsonPropertyName("link")]
        public string? Link { get { return this.LinkOption; } set { this.LinkOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        /* <example>绿川幸</example> */
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RandomAuthorinfo {\n");
            sb.Append("  Bio: ").Append(Bio).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Link: ").Append(Link).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="RandomAuthorinfo" />
    /// </summary>
    public class RandomAuthorinfoJsonConverter : JsonConverter<RandomAuthorinfo>
    {
        /// <summary>
        /// Deserializes json to <see cref="RandomAuthorinfo" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override RandomAuthorinfo Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> bio = default;
            Option<string?> description = default;
            Option<string?> id = default;
            Option<string?> link = default;
            Option<string?> name = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "bio":
                            bio = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "link":
                            link = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (bio.IsSet && bio.Value == null)
                throw new ArgumentNullException(nameof(bio), "Property is not nullable for class RandomAuthorinfo.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class RandomAuthorinfo.");

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class RandomAuthorinfo.");

            if (link.IsSet && link.Value == null)
                throw new ArgumentNullException(nameof(link), "Property is not nullable for class RandomAuthorinfo.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class RandomAuthorinfo.");

            return new RandomAuthorinfo(bio, description, id, link, name);
        }

        /// <summary>
        /// Serializes a <see cref="RandomAuthorinfo" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="randomAuthorinfo"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, RandomAuthorinfo randomAuthorinfo, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, randomAuthorinfo, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="RandomAuthorinfo" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="randomAuthorinfo"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, RandomAuthorinfo randomAuthorinfo, JsonSerializerOptions jsonSerializerOptions)
        {
            if (randomAuthorinfo.BioOption.IsSet && randomAuthorinfo.Bio == null)
                throw new ArgumentNullException(nameof(randomAuthorinfo.Bio), "Property is required for class RandomAuthorinfo.");

            if (randomAuthorinfo.DescriptionOption.IsSet && randomAuthorinfo.Description == null)
                throw new ArgumentNullException(nameof(randomAuthorinfo.Description), "Property is required for class RandomAuthorinfo.");

            if (randomAuthorinfo.IdOption.IsSet && randomAuthorinfo.Id == null)
                throw new ArgumentNullException(nameof(randomAuthorinfo.Id), "Property is required for class RandomAuthorinfo.");

            if (randomAuthorinfo.LinkOption.IsSet && randomAuthorinfo.Link == null)
                throw new ArgumentNullException(nameof(randomAuthorinfo.Link), "Property is required for class RandomAuthorinfo.");

            if (randomAuthorinfo.NameOption.IsSet && randomAuthorinfo.Name == null)
                throw new ArgumentNullException(nameof(randomAuthorinfo.Name), "Property is required for class RandomAuthorinfo.");

            if (randomAuthorinfo.BioOption.IsSet)
                writer.WriteString("bio", randomAuthorinfo.Bio);

            if (randomAuthorinfo.DescriptionOption.IsSet)
                writer.WriteString("description", randomAuthorinfo.Description);

            if (randomAuthorinfo.IdOption.IsSet)
                writer.WriteString("id", randomAuthorinfo.Id);

            if (randomAuthorinfo.LinkOption.IsSet)
                writer.WriteString("link", randomAuthorinfo.Link);

            if (randomAuthorinfo.NameOption.IsSet)
                writer.WriteString("name", randomAuthorinfo.Name);
        }
    }
}
