/*
 * UAPI OpenAPI
 *
 * Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Net.Http;
using Microsoft.Extensions.DependencyInjection;
using uapi-sdk-csharp.Api;
using uapi-sdk-csharp.Model;

namespace uapi-sdk-csharp.Client
{
    /// <summary>
    /// Provides hosting configuration for uapi-sdk-csharp
    /// </summary>
    public class HostConfiguration
    {
        private readonly IServiceCollection _services;
        private readonly JsonSerializerOptions _jsonOptions = new JsonSerializerOptions();

        internal bool HttpClientsAdded { get; private set; }

        /// <summary>
        /// Instantiates the class 
        /// </summary>
        /// <param name="services"></param>
        public HostConfiguration(IServiceCollection services)
        {
            _services = services;
            _jsonOptions.Converters.Add(new JsonStringEnumConverter());
            _jsonOptions.Converters.Add(new DateTimeJsonConverter());
            _jsonOptions.Converters.Add(new DateTimeNullableJsonConverter());
            _jsonOptions.Converters.Add(new DateOnlyJsonConverter());
            _jsonOptions.Converters.Add(new DateOnlyNullableJsonConverter());
            _jsonOptions.Converters.Add(new Base64JsonConverter());
            _jsonOptions.Converters.Add(new DailyRecommendMomentJsonConverter());
            _jsonOptions.Converters.Add(new DailyRecommendMomentItemJsonConverter());
            _jsonOptions.Converters.Add(new DailyRecommendMomentSceneJsonConverter());
            _jsonOptions.Converters.Add(new FormatJsonJsonConverter());
            _jsonOptions.Converters.Add(new FormatJsonTriviaJsonConverter());
            _jsonOptions.Converters.Add(new FormatJsonTriviaOptionsInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetAiTranslateLanguages200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetAiTranslateLanguages200ResponseDataJsonConverter());
            _jsonOptions.Converters.Add(new GetAiTranslateLanguages200ResponseDataContextsInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetAiTranslateLanguages200ResponseDataLanguagesInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetAiTranslateLanguages200ResponseDataStylesInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetAiTranslateLanguages200ResponsePerformanceJsonConverter());
            _jsonOptions.Converters.Add(new GetAnswerbookAsk200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetAnswerbookAsk400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetAnswerbookAsk500ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetAvatarGravatar400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetAvatarGravatar404ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetClipzyGet200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetClipzyGet400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetClipzyGet404ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetClipzyRaw400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetClipzyRaw403ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetConvertUnixtime200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetConvertUnixtime400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetDailyNewsImage500ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetDailyNewsImage502ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetDailyWord200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetDailyWord200ResponseWordsInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetDailyWord200ResponseWordsInnerExamplesInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetDictionaryAudio404ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetDictionaryAudio502ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetDictionaryLookup200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetDictionaryLookup200ResponseEntryJsonConverter());
            _jsonOptions.Converters.Add(new GetDictionaryLookup200ResponseEntryDefinitionsInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetDictionaryLookup200ResponseEntryEnglishDefinitionsInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetDictionaryLookup200ResponseEntryExamplesInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetDictionaryLookup200ResponseEntryPhoneticsJsonConverter());
            _jsonOptions.Converters.Add(new GetDictionaryLookup200ResponseEntryPhoneticsUkJsonConverter());
            _jsonOptions.Converters.Add(new GetDictionaryLookup200ResponseEntryPhoneticsUsJsonConverter());
            _jsonOptions.Converters.Add(new GetDictionaryLookup200ResponseEntryPhrasesInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetDictionaryLookup200ResponseEntrySynonymsInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetDictionaryLookup200ResponseEntryWordFormsInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetDictionaryLookup404ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetDictionaryLookup502ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetGameEpicFree200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetGameEpicFree200ResponseDataInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetGameEpicFree500ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetGameMinecraftHistoryid200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetGameMinecraftHistoryid200ResponseHistoryInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetGameMinecraftHistoryid200ResponseResultsInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetGameMinecraftHistoryid200ResponseResultsInnerHistoryInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetGameMinecraftHistoryid400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetGameMinecraftHistoryid404ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetGameMinecraftHistoryid502ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetGameMinecraftMods200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetGameMinecraftMods200ResponseResultsInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetGameMinecraftServerstatus200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetGameMinecraftServerstatus200ResponseOnlinePlayersInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetGameMinecraftServerstatus400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetGameMinecraftServerstatus404ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetGameMinecraftServerstatus502ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetGameMinecraftUserinfo200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetGameMinecraftUserinfo400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetGameMinecraftUserinfo404ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetGameMinecraftUserinfo502ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetGameMinecraftVersion200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetGameMinecraftVersion200ResponseLatestJsonConverter());
            _jsonOptions.Converters.Add(new GetGameMinecraftVersion200ResponseVersionsInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetGameMinecraftVersion503ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetGameSteamServers200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetGameSteamServers200ResponseServersInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetGameSteamSummary200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetGameSteamSummary400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetGameSteamSummary401ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetGameSteamSummary404ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetGithubRepo200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetGithubRepo200ResponseCollaboratorsInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetGithubRepo200ResponseLatestReleaseJsonConverter());
            _jsonOptions.Converters.Add(new GetGithubRepo400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetGithubRepo502ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetGithubUser200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetGithubUser200ResponseActivityJsonConverter());
            _jsonOptions.Converters.Add(new GetGithubUser200ResponseActivityContributionCalendarJsonConverter());
            _jsonOptions.Converters.Add(new GetGithubUser200ResponseActivityContributionCalendarWeeksInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetGithubUser200ResponseActivityContributionCalendarWeeksInnerContributionDaysInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetGithubUser200ResponseActivityTimelineInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetGithubUser200ResponseOrganizationsInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetGithubUser200ResponsePinnedRepositoriesInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetGithubUser200ResponseRepositoriesInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetGithubUser400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetGithubUser400ResponseOneOfJsonConverter());
            _jsonOptions.Converters.Add(new GetGithubUser400ResponseOneOf1JsonConverter());
            _jsonOptions.Converters.Add(new GetGithubUser404ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetGithubUser502ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetHistoryProgrammer200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetHistoryProgrammer200ResponseEventsInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetHistoryProgrammer400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetHistoryProgrammer500ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetHistoryProgrammerToday200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetHistoryProgrammerToday200ResponseEventsInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetImageBingDaily400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetImageBingDaily404ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetImageBingDaily500ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetImageBingDailyHistory200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetImageBingDailyHistory200ResponseItemsInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetImageBingDailyHistory200ResponsePaginationJsonConverter());
            _jsonOptions.Converters.Add(new GetImageBingDailyHistory400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetImageMotou400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetImageMotou500ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetImageQrcode200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetImageQrcode400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetImageQrcode500ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetImageTobase64200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetImageTobase64400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetImageTobase64502ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscDistrict200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscDistrict200ResponseResultsInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscDistrict200ResponseResultsInnerCenterJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscDistrict400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscHolidayCalendar200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscHolidayCalendar200ResponseDaysInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscHolidayCalendar200ResponseHolidaysInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscHolidayCalendar200ResponseNearbyJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscHolidayCalendar200ResponseNearbyNextInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscHolidayCalendar200ResponseNearbyNextInnerEventsInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscHolidayCalendar200ResponseNearbyPreviousInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscHolidayCalendar200ResponseNearbyPreviousInnerEventsInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscHolidayCalendar200ResponseQueryJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscHolidayCalendar200ResponseSummaryJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscHolidayCalendar400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscHotboard200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscHotboard200ResponseOneOfJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscHotboard200ResponseOneOf1JsonConverter());
            _jsonOptions.Converters.Add(new GetMiscHotboard200ResponseOneOf1ResultsInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscHotboard200ResponseOneOfListInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscHotboard400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscHotboard500ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscHotboard502ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscLunartime200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscLunartime400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscMovieBoxOffice200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscMovieBoxOffice200ResponseListInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscMovieBoxOffice200ResponseMarketJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscMovieBoxOffice503ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscMovieRatingRank200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscMovieRatingRank200ResponseChannelsInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscMovieRatingRank200ResponseChannelsInnerItemsInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscPhoneinfo200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscPhoneinfo400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscPhoneinfo500ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscRandomnumber200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscRandomnumber400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscTimestamp200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscTimestamp400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscTrackingCarriers200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscTrackingCarriers200ResponseCarriersInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscTrackingDetect200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscTrackingDetect200ResponseAlternativesInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscTrackingDetect404ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscTrackingQuery200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscTrackingQuery200ResponseTracksInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscTrackingQuery400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscTrackingQuery404ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscWeather200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscWeather200ResponseAirPollutantsJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscWeather200ResponseAlertsInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscWeather200ResponseForecastInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscWeather200ResponseHourlyForecastInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscWeather200ResponseLifeIndicesJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscWeather200ResponseLifeIndicesAirConditionerJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscWeather200ResponseLifeIndicesAirPurifierJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscWeather200ResponseLifeIndicesAllergyJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscWeather200ResponseLifeIndicesBeerJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscWeather200ResponseLifeIndicesCarWashJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscWeather200ResponseLifeIndicesClothingJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscWeather200ResponseLifeIndicesColdRiskJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscWeather200ResponseLifeIndicesComfortJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscWeather200ResponseLifeIndicesDryingJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscWeather200ResponseLifeIndicesExerciseJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscWeather200ResponseLifeIndicesFishingJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscWeather200ResponseLifeIndicesMoodJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscWeather200ResponseLifeIndicesPollenJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscWeather200ResponseLifeIndicesSunscreenJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscWeather200ResponseLifeIndicesTrafficJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscWeather200ResponseLifeIndicesTravelJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscWeather200ResponseLifeIndicesUmbrellaJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscWeather200ResponseLifeIndicesUvJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscWeather200ResponseMinutelyPrecipJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscWeather200ResponseMinutelyPrecipDataInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscWeather400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscWeather404ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscWeather500ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscWeather503ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscWeatherHistory200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscWeatherHistory200ResponseDaysInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscWorldtime200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscWorldtime400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetMiscWorldtime404ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetNetworkDns200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetNetworkDns200ResponseRecordsInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetNetworkDns400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetNetworkDns404ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetNetworkIcp200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetNetworkIcp404ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetNetworkIpinfo200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetNetworkIpinfo400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetNetworkIpinfo404ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetNetworkIpinfo500ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetNetworkMyip200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetNetworkMyip400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetNetworkMyip500ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetNetworkPing200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetNetworkPing400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetNetworkPing429ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetNetworkPingmyip200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetNetworkPingmyip404ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetNetworkPortscan200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetNetworkPortscan400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetNetworkPortscan500ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetNetworkUrlstatus200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetNetworkUrlstatus200ResponseOneOfJsonConverter());
            _jsonOptions.Converters.Add(new GetNetworkUrlstatus200ResponseOneOf1JsonConverter());
            _jsonOptions.Converters.Add(new GetNetworkUrlstatus502ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetNetworkWhois200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetNetworkWhois200ResponseOneOfJsonConverter());
            _jsonOptions.Converters.Add(new GetNetworkWhois200ResponseOneOf1JsonConverter());
            _jsonOptions.Converters.Add(new GetNetworkWhois404ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetNetworkWxdomain200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetNetworkWxdomain502ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetRandomImage404ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetRandomImage500ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetRandomString200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetRandomString400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetRandomString500ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetSaying200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetSaying500ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetSayingRandom200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetSayingRandom400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetSayingRandom404ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetSearchEngines200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetSearchEngines200ResponseEngineJsonConverter());
            _jsonOptions.Converters.Add(new GetSearchEngines200ResponseLimitsJsonConverter());
            _jsonOptions.Converters.Add(new GetSensitiveWordAnalyzeQuery400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialBilibiliArchives200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialBilibiliArchives200ResponseVideosInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialBilibiliArchives400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialBilibiliArchives404ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialBilibiliArchives500ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialBilibiliLiveroom200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialBilibiliLiveroom200ResponseNewPendantsJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialBilibiliLiveroom200ResponseNewPendantsBadgeJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialBilibiliLiveroom200ResponseNewPendantsFrameJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialBilibiliReplies200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialBilibiliReplies200ResponsePageJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialBilibiliReplies200ResponseRepliesInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialBilibiliReplies200ResponseRepliesInnerContentJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialBilibiliReplies200ResponseRepliesInnerMemberJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialBilibiliReplies200ResponseRepliesInnerMemberLevelInfoJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialBilibiliUserinfo200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialBilibiliUserinfo400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialBilibiliUserinfo404ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialBilibiliUserinfo502ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialBilibiliVideoinfo200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialBilibiliVideoinfo200ResponseDescV2InnerJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialBilibiliVideoinfo200ResponseDimensionJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialBilibiliVideoinfo200ResponseHonorReplyJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialBilibiliVideoinfo200ResponseHonorReplyHonorInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialBilibiliVideoinfo200ResponseOwnerJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialBilibiliVideoinfo200ResponsePagesInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialBilibiliVideoinfo200ResponsePagesInnerDimensionJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialBilibiliVideoinfo200ResponseRightsJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialBilibiliVideoinfo200ResponseStaffInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialBilibiliVideoinfo200ResponseStatJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialBilibiliVideoinfo200ResponseSubtitleJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialBilibiliVideoinfo200ResponseSubtitleListInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialBilibiliVideoinfo200ResponseSubtitleListInnerAuthorJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialBilibiliVideoinfo200ResponseUgcSeasonJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialQqGroupinfo200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialQqGroupinfo400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialQqGroupinfo404ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialQqUserinfo200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialQqUserinfo200ResponsePrivilegeIconsJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialQqUserinfo400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetSocialQqUserinfo404ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetStatusRatelimit200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetStatusRatelimit401ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetStatusUsage200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetStatusUsage200ResponseAnyOfJsonConverter());
            _jsonOptions.Converters.Add(new GetStatusUsage200ResponseAnyOf1JsonConverter());
            _jsonOptions.Converters.Add(new GetStatusUsage200ResponseAnyOfEndpointsInnerJsonConverter());
            _jsonOptions.Converters.Add(new GetStatusUsage200ResponseAnyOfUnaggregatedJsonConverter());
            _jsonOptions.Converters.Add(new GetStatusUsage404ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetTextMd5200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetTextMd5400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetWebTomarkdownAsyncStatus200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetWebTomarkdownAsyncStatus200ResponseAnyOfJsonConverter());
            _jsonOptions.Converters.Add(new GetWebTomarkdownAsyncStatus200ResponseAnyOf1JsonConverter());
            _jsonOptions.Converters.Add(new GetWebTomarkdownAsyncStatus200ResponseAnyOf2JsonConverter());
            _jsonOptions.Converters.Add(new GetWebTomarkdownAsyncStatus200ResponseAnyOf2ResultJsonConverter());
            _jsonOptions.Converters.Add(new GetWebTomarkdownAsyncStatus200ResponseAnyOf3JsonConverter());
            _jsonOptions.Converters.Add(new GetWebTomarkdownAsyncStatus404ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetWebparseExtractimages200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetWebparseExtractimages500ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetWebparseMetadata200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new GetWebparseMetadata500ResponseJsonConverter());
            _jsonOptions.Converters.Add(new HTMLJsonConverter());
            _jsonOptions.Converters.Add(new MarkdownJsonConverter());
            _jsonOptions.Converters.Add(new PostAiTranslate200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostAiTranslate200ResponseDataJsonConverter());
            _jsonOptions.Converters.Add(new PostAiTranslate200ResponsePerformanceJsonConverter());
            _jsonOptions.Converters.Add(new PostAiTranslate400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostAiTranslate401ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostAiTranslate429ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostAiTranslate500ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostAiTranslateRequestJsonConverter());
            _jsonOptions.Converters.Add(new PostAnswerbookAsk200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostAnswerbookAskRequestJsonConverter());
            _jsonOptions.Converters.Add(new PostClipzyStore200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostClipzyStore400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostClipzyStore413ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostClipzyStoreRequestJsonConverter());
            _jsonOptions.Converters.Add(new PostConvertJson200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostConvertJson400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostConvertJsonRequestJsonConverter());
            _jsonOptions.Converters.Add(new PostImageCompress400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostImageCompress500ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostImageDecode400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostImageDecode413ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostImageDecode500ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostImageDecode502ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostImageDecode503ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostImageDecode504ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostImageFrombase64200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostImageFrombase64400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostImageFrombase64500ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostImageFrombase64RequestJsonConverter());
            _jsonOptions.Converters.Add(new PostImageMotou400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostImageMotou500ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostImageNsfw200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostImageNsfw400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostImageNsfw413ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostImageNsfw500ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostImageOcr200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostImageOcr200ResponseWordsResultInnerJsonConverter());
            _jsonOptions.Converters.Add(new PostImageOcr200ResponseWordsResultInnerLocationJsonConverter());
            _jsonOptions.Converters.Add(new PostImageOcr200ResponseWordsResultInnerVertexesLocationInnerJsonConverter());
            _jsonOptions.Converters.Add(new PostImageOcr400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostImageOcr400ResponseOneOfJsonConverter());
            _jsonOptions.Converters.Add(new PostImageOcr400ResponseOneOf1JsonConverter());
            _jsonOptions.Converters.Add(new PostImageOcr413ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostImageOcr415ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostImageOcr502ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostImageOcr503ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostImageSpeechless400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostImageSpeechless500ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostImageSpeechlessRequestJsonConverter());
            _jsonOptions.Converters.Add(new PostImageSvg400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostImageSvg500ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostMiscDateDiff200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostMiscDateDiff400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostMiscDateDiffRequestJsonConverter());
            _jsonOptions.Converters.Add(new PostSearchAggregate200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostSearchAggregate200ResponseMetadataJsonConverter());
            _jsonOptions.Converters.Add(new PostSearchAggregate200ResponseMetadataRequestParamsJsonConverter());
            _jsonOptions.Converters.Add(new PostSearchAggregate200ResponseResultsInnerJsonConverter());
            _jsonOptions.Converters.Add(new PostSearchAggregate200ResponseSourcesInnerJsonConverter());
            _jsonOptions.Converters.Add(new PostSearchAggregate400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostSearchAggregate401ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostSearchAggregate429ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostSearchAggregate500ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostSearchAggregateRequestJsonConverter());
            _jsonOptions.Converters.Add(new PostSensitiveWordAnalyze200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostSensitiveWordAnalyze200ResponseResultsInnerJsonConverter());
            _jsonOptions.Converters.Add(new PostSensitiveWordAnalyze400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostSensitiveWordAnalyze401ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostSensitiveWordAnalyze429ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostSensitiveWordAnalyzeRequestJsonConverter());
            _jsonOptions.Converters.Add(new PostSensitiveWordQuickCheck200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostSensitiveWordQuickCheckRequestJsonConverter());
            _jsonOptions.Converters.Add(new PostTextAesDecrypt200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostTextAesDecrypt400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostTextAesDecrypt500ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostTextAesDecryptAdvanced200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostTextAesDecryptAdvanced400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostTextAesDecryptAdvancedRequestJsonConverter());
            _jsonOptions.Converters.Add(new PostTextAesDecryptRequestJsonConverter());
            _jsonOptions.Converters.Add(new PostTextAesEncrypt200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostTextAesEncrypt400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostTextAesEncrypt500ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostTextAesEncryptAdvanced200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostTextAesEncryptAdvanced400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostTextAesEncryptAdvancedRequestJsonConverter());
            _jsonOptions.Converters.Add(new PostTextAesEncryptRequestJsonConverter());
            _jsonOptions.Converters.Add(new PostTextAnalyze200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostTextAnalyze400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostTextAnalyzeRequestJsonConverter());
            _jsonOptions.Converters.Add(new PostTextBase64Decode200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostTextBase64Decode400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostTextBase64DecodeRequestJsonConverter());
            _jsonOptions.Converters.Add(new PostTextBase64Encode200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostTextBase64Encode400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostTextBase64EncodeRequestJsonConverter());
            _jsonOptions.Converters.Add(new PostTextConvert200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostTextConvert400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostTextConvertRequestJsonConverter());
            _jsonOptions.Converters.Add(new PostTextMarkdownToHtml200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostTextMarkdownToHtml200ResponseDataJsonConverter());
            _jsonOptions.Converters.Add(new PostTextMarkdownToHtml400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostTextMarkdownToHtml400ResponseOneOfJsonConverter());
            _jsonOptions.Converters.Add(new PostTextMarkdownToHtml400ResponseOneOf1JsonConverter());
            _jsonOptions.Converters.Add(new PostTextMarkdownToHtml413ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostTextMarkdownToHtml500ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostTextMarkdownToHtml503ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostTextMarkdownToHtmlRequestJsonConverter());
            _jsonOptions.Converters.Add(new PostTextMarkdownToPdf400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostTextMarkdownToPdf400ResponseOneOfJsonConverter());
            _jsonOptions.Converters.Add(new PostTextMarkdownToPdf400ResponseOneOf1JsonConverter());
            _jsonOptions.Converters.Add(new PostTextMarkdownToPdf400ResponseOneOf2JsonConverter());
            _jsonOptions.Converters.Add(new PostTextMarkdownToPdf400ResponseOneOf3JsonConverter());
            _jsonOptions.Converters.Add(new PostTextMarkdownToPdf413ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostTextMarkdownToPdf413ResponseOneOfJsonConverter());
            _jsonOptions.Converters.Add(new PostTextMarkdownToPdf500ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostTextMarkdownToPdf502ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostTextMarkdownToPdf503ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostTextMarkdownToPdf503ResponseOneOfJsonConverter());
            _jsonOptions.Converters.Add(new PostTextMarkdownToPdf503ResponseOneOf1JsonConverter());
            _jsonOptions.Converters.Add(new PostTextMarkdownToPdf504ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostTextMarkdownToPdfRequestJsonConverter());
            _jsonOptions.Converters.Add(new PostTextMd5400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostTextMd5RequestJsonConverter());
            _jsonOptions.Converters.Add(new PostTextMd5Verify200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostTextMd5Verify400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostTextMd5VerifyRequestJsonConverter());
            _jsonOptions.Converters.Add(new PostTranslateStream400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostTranslateStream500ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostTranslateStreamRequestJsonConverter());
            _jsonOptions.Converters.Add(new PostTranslateText200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostTranslateText400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostTranslateText500ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostTranslateTextRequestJsonConverter());
            _jsonOptions.Converters.Add(new PostWatermarkDecode200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostWatermarkDecode400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostWatermarkDecode503ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostWatermarkEmbed200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostWatermarkEmbed413ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostWatermarkLabel200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostWatermarkLabel400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostWatermarkProducerCode200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostWatermarkProducerCode400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostWatermarkProducerCodeRequestJsonConverter());
            _jsonOptions.Converters.Add(new PostWebTomarkdownAsync202ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PostWebTomarkdownAsync400ResponseJsonConverter());
            _jsonOptions.Converters.Add(new RandomJsonConverter());
            _jsonOptions.Converters.Add(new RandomAuthorinfoJsonConverter());
            JsonSerializerOptionsProvider jsonSerializerOptionsProvider = new(_jsonOptions);
            _services.AddSingleton(jsonSerializerOptionsProvider);
            _services.AddSingleton<IApiFactory, ApiFactory>();
            _services.AddSingleton<DefaultApiEvents>();
            _services.AddSingleton<AIGCApiEvents>();
            _services.AddSingleton<ClipzyApiEvents>();
            _services.AddSingleton<ConvertApiEvents>();
            _services.AddSingleton<DailyApiEvents>();
            _services.AddSingleton<DictionaryApiEvents>();
            _services.AddSingleton<GameApiEvents>();
            _services.AddSingleton<ImageApiEvents>();
            _services.AddSingleton<MiscApiEvents>();
            _services.AddSingleton<NetworkApiEvents>();
            _services.AddSingleton<PoemApiEvents>();
            _services.AddSingleton<RandomApiEvents>();
            _services.AddSingleton<SocialApiEvents>();
            _services.AddSingleton<StatusApiEvents>();
            _services.AddSingleton<TextApiEvents>();
            _services.AddSingleton<TranslateApiEvents>();
            _services.AddSingleton<WebParseApiEvents>();
        }

        /// <summary>
        /// Configures the HttpClients.
        /// </summary>
        /// <param name="client"></param>
        /// <param name="builder"></param>
        /// <returns></returns>
        public HostConfiguration AddApiHttpClients
        (
            Action<HttpClient>? client = null, Action<IHttpClientBuilder>? builder = null)
        {
            if (client == null)
                client = c => c.BaseAddress = new Uri(ClientUtils.BASE_ADDRESS);

            List<IHttpClientBuilder> builders = new List<IHttpClientBuilder>();

            builders.Add(_services.AddHttpClient<IDefaultApi, DefaultApi>(client));
            builders.Add(_services.AddHttpClient<IAIGCApi, AIGCApi>(client));
            builders.Add(_services.AddHttpClient<IClipzyApi, ClipzyApi>(client));
            builders.Add(_services.AddHttpClient<IConvertApi, ConvertApi>(client));
            builders.Add(_services.AddHttpClient<IDailyApi, DailyApi>(client));
            builders.Add(_services.AddHttpClient<IDictionaryApi, DictionaryApi>(client));
            builders.Add(_services.AddHttpClient<IGameApi, GameApi>(client));
            builders.Add(_services.AddHttpClient<IImageApi, ImageApi>(client));
            builders.Add(_services.AddHttpClient<IMiscApi, MiscApi>(client));
            builders.Add(_services.AddHttpClient<INetworkApi, NetworkApi>(client));
            builders.Add(_services.AddHttpClient<IPoemApi, PoemApi>(client));
            builders.Add(_services.AddHttpClient<IRandomApi, RandomApi>(client));
            builders.Add(_services.AddHttpClient<ISocialApi, SocialApi>(client));
            builders.Add(_services.AddHttpClient<IStatusApi, StatusApi>(client));
            builders.Add(_services.AddHttpClient<ITextApi, TextApi>(client));
            builders.Add(_services.AddHttpClient<ITranslateApi, TranslateApi>(client));
            builders.Add(_services.AddHttpClient<IWebParseApi, WebParseApi>(client));
            
            if (builder != null)
                foreach (IHttpClientBuilder instance in builders)
                    builder(instance);

            HttpClientsAdded = true;

            return this;
        }

        /// <summary>
        /// Configures the JsonSerializerSettings
        /// </summary>
        /// <param name="options"></param>
        /// <returns></returns>
        public HostConfiguration ConfigureJsonOptions(Action<JsonSerializerOptions> options)
        {
            options(_jsonOptions);

            return this;
        }

        /// <summary>
        /// Adds tokens to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <param name="token"></param>
        /// <returns></returns>
        public HostConfiguration AddTokens<TTokenBase>(TTokenBase token) where TTokenBase : TokenBase
        {
            return AddTokens(new TTokenBase[]{ token });
        }

        /// <summary>
        /// Adds tokens to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <param name="tokens"></param>
        /// <returns></returns>
        public HostConfiguration AddTokens<TTokenBase>(IEnumerable<TTokenBase> tokens) where TTokenBase : TokenBase
        {
            TokenContainer<TTokenBase> container = new TokenContainer<TTokenBase>(tokens);
            _services.AddSingleton(services => container);

            return this;
        }

        /// <summary>
        /// Adds a token provider to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenProvider"></typeparam>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <returns></returns>
        public HostConfiguration UseProvider<TTokenProvider, TTokenBase>() 
            where TTokenProvider : TokenProvider<TTokenBase>
            where TTokenBase : TokenBase
        {
            _services.AddSingleton<TTokenProvider>();
            _services.AddSingleton<TokenProvider<TTokenBase>>(services => services.GetRequiredService<TTokenProvider>());

            return this;
        }
    }
}
